# This file is auto-generated by scripts/generate_client_pyi.py.
# Do not edit this file directly.
# Sources: endpoint manifest, HandleMixin assembly, and domain endpoint mixins.
# Source SHA256: eba811d7ae0da543a573a752f3047f3920ed8d08a43476b84ca701e8ccbfeb29

from datetime import datetime
from typing import Any, Literal, TypeAlias, overload
from typing_extensions import Unpack

from .model import (
    SKU,
    ActivityInstance,
    AddGroupDMRecipientParams,
    AddGuildMemberParams,
    AddLobbyMemberParams,
    AnswerVoters,
    Application,
    ApplicationCommand,
    ApplicationCommandBulkOverwriteParams,
    ApplicationCommandCreate,
    ApplicationCommandEditParams,
    ApplicationEmojis,
    ApplicationRoleConnection,
    ApplicationRoleConnectionMetadata,
    ArchivedThreadsResponse,
    AuditLog,
    AuthorizationResponse,
    AutoModerationAction,
    AutoModerationRule,
    Ban,
    BeginGuildPruneParams,
    BulkBan,
    BulkDeleteMessagesParams,
    BulkGuildBanParams,
    Channel,
    Connection,
    CreateApplicationEmojiParams,
    CreateChannelInviteParams,
    CreateDMParams,
    CreateGroupDMParams,
    CreateGuildChannelParams,
    CreateGuildEmojiParams,
    CreateGuildParams,
    CreateGuildRoleParams,
    CreateGuildScheduledEventParams,
    CreateGuildSoundboardSoundParams,
    CreateGuildTemplateParams,
    CreateLobbyParams,
    CreateStageInstanceParams,
    CreateTestEntitlementParams,
    CreateWebhookParams,
    CurrentUserGuild,
    EditApplicationCommandPermissionsParams,
    EditChannelPermissionsParams,
    EditCurrentApplicationParams,
    Emoji,
    Entitlement,
    ExecuteWebhookParams,
    File,
    FollowAnnouncementChannelParams,
    FollowedChannel,
    Gateway,
    GatewayBot,
    Guild,
    GuildApplicationCommandPermissions,
    GuildIncidentsData,
    GuildMember,
    GuildOnboarding,
    GuildPreview,
    GuildScheduledEvent,
    GuildScheduledEventUser,
    GuildTemplate,
    GuildVanityURL,
    GuildWidget,
    GuildWidgetSettings,
    Integration,
    InteractionResponse,
    Invite,
    InviteTargetUsersJobStatus,
    LinkChannelToLobbyParams,
    ListActiveGuildThreadsResponse,
    ListDefaultSoundboardSoundsResponse,
    ListGuildSoundboardSoundsResponse,
    Lobby,
    LobbyMember,
    MessageEditParams,
    MessageGet,
    MessageSend,
    ModifyApplicationEmojiParams,
    ModifyAutoModerationRuleParams,
    ModifyChannelParams,
    ModifyCurrentMemberParams,
    ModifyCurrentUserNickParams,
    ModifyCurrentUserParams,
    ModifyCurrentUserVoiceStateParams,
    ModifyDMParams,
    ModifyGuildChannelPositionParams,
    ModifyGuildEmojiParams,
    ModifyGuildIncidentActionsParams,
    ModifyGuildMemberParams,
    ModifyGuildMFAParams,
    ModifyGuildOnboardingParams,
    ModifyGuildParams,
    ModifyGuildRoleParams,
    ModifyGuildRolePositionParams,
    ModifyGuildScheduledEventParams,
    ModifyGuildSoundboardSoundParams,
    ModifyGuildStickerParams,
    ModifyGuildTemplateParams,
    ModifyGuildWelcomeScreenParams,
    ModifyGuildWidgetParams,
    ModifyLobbyParams,
    ModifyStageInstanceParams,
    ModifyThreadParams,
    ModifyUserVoiceStateParams,
    ModifyWebhookParams,
    Role,
    SendSoundboardSoundParams,
    Snowflake,
    SnowflakeType,
    SoundboardSound,
    StageInstance,
    StartThreadFromMessageParams,
    StartThreadWithoutMessageParams,
    Sticker,
    StickerPack,
    StickerPacksResponse,
    Subscription,
    ThreadMember,
    TriggerMetadata,
    UnsetType,
    UpdateUserApplicationRoleConnectionParams,
    User,
    VoiceRegion,
    VoiceState,
    Webhook,
    WebhookMessageEditParams,
    WelcomeScreen,
)
from .types import (
    AuditLogEventType,
    AutoModerationRuleEventType,
    ReactionType,
    TriggerType,
)

NonSpamTriggerType: TypeAlias = Literal[
    TriggerType.KEYWORD,
    TriggerType.KEYWORD_PRESET,
    TriggerType.MENTION_SPAM,
    TriggerType.MEMBER_PROFILE,
]

class ApiClient:
    async def get_global_application_commands(
        self,
        *,
        application_id: SnowflakeType,
        with_localizations: bool | None = None,
    ) -> list[ApplicationCommand]:
        """Get global application commands.

        see https://discord.com/developers/docs/interactions/application-commands#get-global-application-commands
        """

    async def create_global_application_command(
        self,
        *,
        application_id: SnowflakeType,
        **fields: Unpack[ApplicationCommandCreate],
    ) -> ApplicationCommand:
        """Create global application command.

        see https://discord.com/developers/docs/interactions/application-commands#create-global-application-command
        """

    async def get_global_application_command(
        self,
        *,
        application_id: SnowflakeType,
        command_id: SnowflakeType,
    ) -> ApplicationCommand:
        """Get global application command.

        see https://discord.com/developers/docs/interactions/application-commands#get-global-application-command
        """

    async def edit_global_application_command(
        self,
        *,
        application_id: SnowflakeType,
        command_id: SnowflakeType,
        **fields: Unpack[ApplicationCommandEditParams],
    ) -> ApplicationCommand:
        """Edit global application command.

        see https://discord.com/developers/docs/interactions/application-commands#edit-global-application-command
        """

    async def delete_global_application_command(
        self,
        *,
        application_id: SnowflakeType,
        command_id: SnowflakeType,
    ) -> None:
        """Delete global application command.

        see https://discord.com/developers/docs/interactions/application-commands#delete-global-application-command
        """

    async def bulk_overwrite_global_application_commands(
        self,
        *,
        application_id: SnowflakeType,
        commands: list[ApplicationCommandBulkOverwriteParams],
    ) -> list[ApplicationCommand]:
        """Bulk overwrite global application commands.

        see https://discord.com/developers/docs/interactions/application-commands#bulk-overwrite-global-application-commands
        """

    async def get_guild_application_commands(
        self,
        *,
        application_id: SnowflakeType,
        guild_id: SnowflakeType,
        with_localizations: bool | None = None,
    ) -> list[ApplicationCommand]:
        """Get guild application commands.

        see https://discord.com/developers/docs/interactions/application-commands#get-guild-application-commands
        """

    async def create_guild_application_command(
        self,
        *,
        application_id: SnowflakeType,
        guild_id: SnowflakeType,
        **fields: Unpack[ApplicationCommandCreate],
    ) -> ApplicationCommand:
        """Create guild application command.

        see https://discord.com/developers/docs/interactions/application-commands#create-guild-application-command
        """

    async def get_guild_application_command(
        self,
        *,
        application_id: SnowflakeType,
        guild_id: SnowflakeType,
        command_id: SnowflakeType,
    ) -> ApplicationCommand:
        """Get guild application command.

        see https://discord.com/developers/docs/interactions/application-commands#get-guild-application-command
        """

    async def edit_guild_application_command(
        self,
        *,
        application_id: SnowflakeType,
        guild_id: SnowflakeType,
        command_id: SnowflakeType,
        **fields: Unpack[ApplicationCommandEditParams],
    ) -> ApplicationCommand:
        """Edit guild application command.

        see https://discord.com/developers/docs/interactions/application-commands#edit-guild-application-command
        """

    async def delete_guild_application_command(
        self,
        *,
        application_id: SnowflakeType,
        guild_id: SnowflakeType,
        command_id: SnowflakeType,
    ) -> None:
        """Delete guild application command.

        see https://discord.com/developers/docs/interactions/application-commands#delete-guild-application-command
        """

    async def bulk_overwrite_guild_application_commands(
        self,
        *,
        application_id: SnowflakeType,
        guild_id: SnowflakeType,
        commands: list[ApplicationCommandBulkOverwriteParams],
    ) -> list[ApplicationCommand]:
        """Bulk overwrite guild application commands.

        see https://discord.com/developers/docs/interactions/application-commands#bulk-overwrite-guild-application-commands
        """

    async def get_guild_application_command_permissions(
        self,
        *,
        application_id: SnowflakeType,
        guild_id: SnowflakeType,
        access_token: str,
    ) -> list[GuildApplicationCommandPermissions]:
        """Get guild application command permissions.

        see https://discord.com/developers/docs/interactions/application-commands#get-guild-application-command-permissions
        """

    async def get_application_command_permissions(
        self,
        *,
        application_id: SnowflakeType,
        guild_id: SnowflakeType,
        command_id: SnowflakeType,
        access_token: str,
    ) -> GuildApplicationCommandPermissions:
        """Get application command permissions.

        see https://discord.com/developers/docs/interactions/application-commands#get-application-command-permissions
        """

    async def edit_application_command_permissions(
        self,
        *,
        application_id: SnowflakeType,
        guild_id: SnowflakeType,
        command_id: SnowflakeType,
        access_token: str,
        **fields: Unpack[EditApplicationCommandPermissionsParams],
    ) -> GuildApplicationCommandPermissions:
        """Edit application command permissions.

        see https://discord.com/developers/docs/interactions/application-commands#edit-application-command-permissions
        """

    async def create_interaction_response(
        self,
        *,
        interaction_id: SnowflakeType,
        interaction_token: str,
        response: InteractionResponse,
        with_response: bool | None = None,
    ) -> InteractionResponse | None:
        """Create an interaction response.

        see https://discord.com/developers/docs/interactions/receiving-and-responding#create-interaction-response
        """

    async def get_origin_interaction_response(
        self,
        *,
        application_id: SnowflakeType,
        interaction_token: str,
        thread_id: SnowflakeType | None = None,
    ) -> MessageGet:
        """Get the original interaction response.

        see https://discord.com/developers/docs/interactions/receiving-and-responding#get-original-interaction-response
        """

    async def edit_origin_interaction_response(
        self,
        *,
        application_id: SnowflakeType,
        interaction_token: str,
        thread_id: SnowflakeType | None = None,
        with_components: bool | None = None,
        **fields: Unpack[WebhookMessageEditParams],
    ) -> MessageGet:
        """Edit the original interaction response.

        see https://discord.com/developers/docs/interactions/receiving-and-responding#edit-original-interaction-response
        """

    async def delete_origin_interaction_response(
        self,
        *,
        application_id: SnowflakeType,
        interaction_token: str,
        thread_id: SnowflakeType | None = None,
    ) -> None:
        """Delete the original interaction response.

        see https://discord.com/developers/docs/interactions/receiving-and-responding#delete-original-interaction-response
        """

    async def create_followup_message(
        self,
        *,
        application_id: SnowflakeType,
        interaction_token: str,
        **fields: Unpack[ExecuteWebhookParams],
    ) -> MessageGet:
        """Create a followup message.

        see https://discord.com/developers/docs/interactions/receiving-and-responding#create-followup-message
        """

    async def get_followup_message(
        self,
        *,
        application_id: SnowflakeType,
        interaction_token: str,
        message_id: SnowflakeType,
        thread_id: SnowflakeType | None = None,
    ) -> MessageGet:
        """Get a followup message.

        see https://discord.com/developers/docs/interactions/receiving-and-responding#get-followup-message
        """

    async def edit_followup_message(
        self,
        *,
        application_id: SnowflakeType,
        interaction_token: str,
        message_id: SnowflakeType,
        thread_id: SnowflakeType | None = None,
        with_components: bool | None = None,
        **fields: Unpack[WebhookMessageEditParams],
    ) -> MessageGet:
        """Edit a followup message.

        see https://discord.com/developers/docs/interactions/receiving-and-responding#edit-followup-message
        """

    async def delete_followup_message(
        self,
        *,
        application_id: SnowflakeType,
        interaction_token: str,
        message_id: SnowflakeType,
        thread_id: SnowflakeType | None = None,
    ) -> None:
        """Delete a followup message.

        see https://discord.com/developers/docs/interactions/receiving-and-responding#delete-followup-message
        """

    async def get_current_application(
        self,
    ) -> Application:
        """Get current application.

        see https://discord.com/developers/docs/resources/application#get-current-application
        """

    async def edit_current_application(
        self,
        **fields: Unpack[EditCurrentApplicationParams],
    ) -> Application:
        """Edit current application.

        see https://discord.com/developers/docs/resources/application#edit-current-application
        """

    async def get_application_activity_instance(
        self,
        *,
        application_id: SnowflakeType,
        instance_id: str,
    ) -> ActivityInstance:
        """Get application activity instance.

        see https://discord.com/developers/docs/resources/application#get-application-activity-instance
        """

    async def get_application_role_connection_metadata_records(
        self,
        *,
        application_id: SnowflakeType,
    ) -> list[ApplicationRoleConnectionMetadata]:
        """Get application role connection metadata records.

        see https://discord.com/developers/docs/resources/application-role-connection-metadata#get-application-role-connection-metadata-records
        """

    async def update_application_role_connection_metadata_records(
        self,
        *,
        application_id: SnowflakeType,
        records: list[ApplicationRoleConnectionMetadata],
    ) -> list[ApplicationRoleConnectionMetadata]:
        """Update application role connection metadata records.

        see https://discord.com/developers/docs/resources/application-role-connection-metadata#update-application-role-connection-metadata-records
        """

    @overload
    async def get_guild_audit_log(
        self,
        *,
        guild_id: SnowflakeType,
        user_id: SnowflakeType | None = None,
        action_type: AuditLogEventType | None = None,
        before: SnowflakeType | None = None,
        after: None = None,
        limit: int | None = None,
    ) -> AuditLog: ...
    @overload
    async def get_guild_audit_log(
        self,
        *,
        guild_id: SnowflakeType,
        user_id: SnowflakeType | None = None,
        action_type: AuditLogEventType | None = None,
        before: None = None,
        after: SnowflakeType | None = None,
        limit: int | None = None,
    ) -> AuditLog: ...
    async def list_auto_moderation_rules_for_guild(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> list[AutoModerationRule]:
        """List auto moderation rules for guild.

        see https://discord.com/developers/docs/resources/auto-moderation#list-auto-moderation-rules-for-guild
        """

    async def get_auto_moderation_rule(
        self,
        *,
        guild_id: SnowflakeType,
        rule_id: SnowflakeType,
    ) -> AutoModerationRule:
        """Get auto moderation rule.

        see https://discord.com/developers/docs/resources/auto-moderation#get-auto-moderation-rule
        """

    @overload
    async def create_auto_moderation_rule(
        self,
        *,
        guild_id: SnowflakeType,
        name: str,
        event_type: AutoModerationRuleEventType,
        trigger_type: Literal[TriggerType.SPAM],
        actions: list[AutoModerationAction],
        enabled: bool = ...,
        exempt_roles: list[SnowflakeType] = ...,
        exempt_channels: list[SnowflakeType] = ...,
        reason: str | None = None,
    ) -> AutoModerationRule: ...
    @overload
    async def create_auto_moderation_rule(
        self,
        *,
        guild_id: SnowflakeType,
        name: str,
        event_type: AutoModerationRuleEventType,
        trigger_type: NonSpamTriggerType,
        actions: list[AutoModerationAction],
        trigger_metadata: TriggerMetadata,
        enabled: bool = ...,
        exempt_roles: list[SnowflakeType] = ...,
        exempt_channels: list[SnowflakeType] = ...,
        reason: str | None = None,
    ) -> AutoModerationRule: ...
    async def modify_auto_moderation_rule(
        self,
        *,
        guild_id: SnowflakeType,
        rule_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[ModifyAutoModerationRuleParams],
    ) -> AutoModerationRule:
        """Modify auto moderation rule.

        see https://discord.com/developers/docs/resources/auto-moderation#modify-auto-moderation-rule
        """

    async def delete_auto_moderation_rule(
        self,
        *,
        guild_id: SnowflakeType,
        rule_id: SnowflakeType,
        reason: str | None = None,
    ) -> None:
        """Delete auto moderation rule.

        see https://discord.com/developers/docs/resources/auto-moderation#delete-auto-moderation-rule
        """

    async def get_channel(
        self,
        *,
        channel_id: SnowflakeType,
    ) -> Channel:
        """Get a channel by ID.

        see https://discord.com/developers/docs/resources/channel#get-channel
        """

    async def modify_DM(
        self,
        *,
        channel_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[ModifyDMParams],
    ) -> Channel:
        """Update a Group DM channel's settings.

        see https://discord.com/developers/docs/resources/channel#modify-channel
        """

    async def modify_channel(
        self,
        *,
        channel_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[ModifyChannelParams],
    ) -> Channel:
        """Update a channel's settings.

        see https://discord.com/developers/docs/resources/channel#modify-channel
        """

    async def modify_thread(
        self,
        *,
        channel_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[ModifyThreadParams],
    ) -> Channel:
        """Update a thread's settings.

        see https://discord.com/developers/docs/resources/channel#modify-channel
        """

    async def delete_channel(
        self,
        *,
        channel_id: SnowflakeType,
        reason: str | None = None,
    ) -> Channel:
        """Delete or close a channel.

        see https://discord.com/developers/docs/resources/channel#delete/close-channel
        """

    @overload
    async def get_channel_messages(
        self,
        *,
        channel_id: SnowflakeType,
        around: SnowflakeType | None = None,
        before: None = None,
        after: None = None,
        limit: int | None = None,
    ) -> list[MessageGet]: ...
    @overload
    async def get_channel_messages(
        self,
        *,
        channel_id: SnowflakeType,
        around: None = None,
        before: SnowflakeType | None = None,
        after: None = None,
        limit: int | None = None,
    ) -> list[MessageGet]: ...
    @overload
    async def get_channel_messages(
        self,
        *,
        channel_id: SnowflakeType,
        around: None = None,
        before: None = None,
        after: SnowflakeType | None = None,
        limit: int | None = None,
    ) -> list[MessageGet]: ...
    async def get_channel_message(
        self,
        *,
        channel_id: SnowflakeType,
        message_id: SnowflakeType,
    ) -> MessageGet:
        """Get a channel message.

        see https://discord.com/developers/docs/resources/message#get-channel-message
        """

    async def create_message(
        self,
        *,
        channel_id: SnowflakeType,
        **fields: Unpack[MessageSend],
    ) -> MessageGet:
        """Create a message.

        see https://discord.com/developers/docs/resources/message#create-message
        """

    async def crosspost_message(
        self,
        *,
        channel_id: SnowflakeType,
        message_id: SnowflakeType,
    ) -> MessageGet:
        """Crosspost a message.

        see https://discord.com/developers/docs/resources/message#crosspost-message
        """

    async def create_reaction(
        self,
        *,
        channel_id: SnowflakeType,
        message_id: SnowflakeType,
        emoji: str,
        emoji_id: SnowflakeType | None = None,
    ) -> None:
        """Create a reaction.

        see https://discord.com/developers/docs/resources/message#create-reaction
        """

    async def delete_own_reaction(
        self,
        *,
        channel_id: SnowflakeType,
        message_id: SnowflakeType,
        emoji: str,
        emoji_id: SnowflakeType | None = None,
    ) -> None:
        """Delete own reaction.

        see https://discord.com/developers/docs/resources/message#delete-own-reaction
        """

    async def delete_user_reaction(
        self,
        *,
        channel_id: SnowflakeType,
        message_id: SnowflakeType,
        user_id: SnowflakeType,
        emoji: str,
        emoji_id: SnowflakeType | None = None,
    ) -> None:
        """Delete a user reaction.

        see https://discord.com/developers/docs/resources/message#delete-user-reaction
        """

    async def get_reactions(
        self,
        *,
        channel_id: SnowflakeType,
        message_id: SnowflakeType,
        emoji: str,
        emoji_id: SnowflakeType | None = None,
        type: ReactionType | None = None,
        after: SnowflakeType | None = None,
        limit: int | None = None,
    ) -> list[User]:
        """Get reactions.

        see https://discord.com/developers/docs/resources/message#get-reactions
        """

    async def delete_all_reactions(
        self,
        *,
        channel_id: SnowflakeType,
        message_id: SnowflakeType,
    ) -> None:
        """Delete all reactions.

        see https://discord.com/developers/docs/resources/message#delete-all-reactions
        """

    async def delete_all_reactions_for_emoji(
        self,
        *,
        channel_id: SnowflakeType,
        message_id: SnowflakeType,
        emoji: str,
        emoji_id: SnowflakeType | None = None,
    ) -> None:
        """Delete all reactions for emoji.

        see https://discord.com/developers/docs/resources/message#delete-all-reactions-for-emoji
        """

    async def edit_message(
        self,
        *,
        channel_id: SnowflakeType,
        message_id: SnowflakeType,
        **fields: Unpack[MessageEditParams],
    ) -> MessageGet:
        """Edit a message.

        see https://discord.com/developers/docs/resources/message#edit-message
        """

    async def delete_message(
        self,
        *,
        channel_id: SnowflakeType,
        message_id: SnowflakeType,
        reason: str | None = None,
    ) -> None:
        """Delete a message.

        see https://discord.com/developers/docs/resources/message#delete-message
        """

    async def bulk_delete_message(
        self,
        *,
        channel_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[BulkDeleteMessagesParams],
    ) -> None:
        """Bulk delete messages.

        see https://discord.com/developers/docs/resources/message#bulk-delete-messages
        """

    async def edit_channel_permissions(
        self,
        *,
        channel_id: SnowflakeType,
        overwrite_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[EditChannelPermissionsParams],
    ) -> None:
        """Edit channel permissions.

        see https://discord.com/developers/docs/resources/channel#edit-channel-permissions
        """

    async def get_channel_invites(
        self,
        *,
        channel_id: SnowflakeType,
    ) -> list[Invite]:
        """Get channel invites.

        see https://discord.com/developers/docs/resources/channel#get-channel-invites
        """

    async def create_channel_invite(
        self,
        *,
        channel_id: SnowflakeType,
        target_users_file: File | None = None,
        reason: str | None = None,
        **fields: Unpack[CreateChannelInviteParams],
    ) -> Invite:
        """Create channel invite.

        see https://discord.com/developers/docs/resources/channel#create-channel-invite
        """

    async def delete_channel_permission(
        self,
        *,
        channel_id: SnowflakeType,
        overwrite_id: SnowflakeType,
        reason: str | None = None,
    ) -> None:
        """Delete channel permission.

        see https://discord.com/developers/docs/resources/channel#delete-channel-permission
        """

    async def follow_announcement_channel(
        self,
        *,
        channel_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[FollowAnnouncementChannelParams],
    ) -> FollowedChannel:
        """Follow announcement channel.

        see https://discord.com/developers/docs/resources/channel#follow-announcement-channel
        """

    async def trigger_typing_indicator(
        self,
        *,
        channel_id: SnowflakeType,
    ) -> None:
        """Trigger typing indicator.

        see https://discord.com/developers/docs/resources/channel#trigger-typing-indicator
        """

    async def get_pinned_messages(
        self,
        *,
        channel_id: SnowflakeType,
    ) -> list[MessageGet]:
        """Get pinned messages.

        see https://discord.com/developers/docs/resources/message#get-channel-pins
        """

    async def pin_message(
        self,
        *,
        channel_id: SnowflakeType,
        message_id: SnowflakeType,
        reason: str | None = None,
    ) -> None:
        """Pin message.

        see https://discord.com/developers/docs/resources/message#pin-message
        """

    async def unpin_message(
        self,
        *,
        channel_id: SnowflakeType,
        message_id: SnowflakeType,
        reason: str | None = None,
    ) -> None:
        """Unpin message.

        see https://discord.com/developers/docs/resources/message#unpin-message
        """

    async def group_DM_add_recipient(
        self,
        *,
        channel_id: SnowflakeType,
        user_id: SnowflakeType,
        **fields: Unpack[AddGroupDMRecipientParams],
    ) -> None:
        """Group DM add recipient.

        see https://discord.com/developers/docs/resources/channel#group-dm-add-recipient
        """

    async def group_DM_remove_recipient(
        self,
        *,
        channel_id: SnowflakeType,
        user_id: SnowflakeType,
    ) -> None:
        """Group DM remove recipient.

        see https://discord.com/developers/docs/resources/channel#group-dm-remove-recipient
        """

    async def start_thread_from_message(
        self,
        *,
        channel_id: SnowflakeType,
        message_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[StartThreadFromMessageParams],
    ) -> Channel:
        """Start thread from message.

        see https://discord.com/developers/docs/resources/channel#start-thread-from-message
        """

    async def start_thread_without_message(
        self,
        *,
        channel_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[StartThreadWithoutMessageParams],
    ) -> Channel:
        """Start thread without message.

        see https://discord.com/developers/docs/resources/channel#start-thread-without-message
        """

    async def start_thread_in_forum_channel(
        self,
        *,
        channel_id: SnowflakeType,
        name: str,
        auto_archive_duration: int | None = None,
        rate_limit_per_user: int | None = None,
        applied_tags: list[Snowflake] | None = None,
        reason: str | None = None,
        **fields: Unpack[MessageSend],
    ) -> Channel:
        """Start thread in forum or media channel.

        see https://discord.com/developers/docs/resources/channel#start-thread-in-forum-or-media-channel
        """

    async def join_thread(
        self,
        *,
        channel_id: SnowflakeType,
    ) -> None:
        """Join thread.

        see https://discord.com/developers/docs/resources/channel#join-thread
        """

    async def add_thread_member(
        self,
        *,
        channel_id: SnowflakeType,
        user_id: SnowflakeType,
    ) -> None:
        """Add thread member.

        see https://discord.com/developers/docs/resources/channel#add-thread-member
        """

    async def leave_thread(
        self,
        *,
        channel_id: SnowflakeType,
    ) -> None:
        """Leave thread.

        see https://discord.com/developers/docs/resources/channel#leave-thread
        """

    async def remove_thread_member(
        self,
        *,
        channel_id: SnowflakeType,
        user_id: SnowflakeType,
    ) -> None:
        """Remove thread member.

        see https://discord.com/developers/docs/resources/channel#remove-thread-member
        """

    async def get_thread_member(
        self,
        *,
        channel_id: SnowflakeType,
        user_id: SnowflakeType,
        with_member: bool | None = None,
    ) -> ThreadMember:
        """Get thread member.

        see https://discord.com/developers/docs/resources/channel#get-thread-member
        """

    async def list_thread_members(
        self,
        *,
        channel_id: SnowflakeType,
        with_member: bool | None = None,
        after: SnowflakeType | None = None,
        limit: int | None = None,
    ) -> list[ThreadMember]:
        """List thread members.

        see https://discord.com/developers/docs/resources/channel#list-thread-members
        """

    async def list_public_archived_threads(
        self,
        *,
        channel_id: SnowflakeType,
        before: datetime | None = None,
        limit: int | None = None,
    ) -> ArchivedThreadsResponse:
        """List public archived threads.

        see https://discord.com/developers/docs/resources/channel#list-public-archived-threads
        """

    async def list_private_archived_threads(
        self,
        *,
        channel_id: SnowflakeType,
        before: datetime | None = None,
        limit: int | None = None,
    ) -> ArchivedThreadsResponse:
        """List private archived threads.

        see https://discord.com/developers/docs/resources/channel#list-private-archived-threads
        """

    async def list_joined_private_archived_threads(
        self,
        *,
        channel_id: SnowflakeType,
        before: SnowflakeType | None = None,
        limit: int | None = None,
    ) -> ArchivedThreadsResponse:
        """List joined private archived threads.

        see https://discord.com/developers/docs/resources/channel#list-joined-private-archived-threads
        """

    async def list_guild_emojis(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> list[Emoji]:
        """List guild emojis.

        see https://discord.com/developers/docs/resources/emoji#list-guild-emojis
        """

    async def get_guild_emoji(
        self,
        *,
        guild_id: SnowflakeType,
        emoji_id: SnowflakeType,
    ) -> Emoji:
        """Get guild emoji.

        see https://discord.com/developers/docs/resources/emoji#get-guild-emoji
        """

    async def create_guild_emoji(
        self,
        *,
        guild_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[CreateGuildEmojiParams],
    ) -> Emoji:
        """Create guild emoji.

        see https://discord.com/developers/docs/resources/emoji#create-guild-emoji
        """

    async def modify_guild_emoji(
        self,
        *,
        guild_id: SnowflakeType,
        emoji_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[ModifyGuildEmojiParams],
    ) -> Emoji:
        """Modify guild emoji.

        see https://discord.com/developers/docs/resources/emoji#modify-guild-emoji
        """

    async def delete_guild_emoji(
        self,
        *,
        guild_id: SnowflakeType,
        emoji_id: SnowflakeType,
        reason: str | None = None,
    ) -> None:
        """Delete guild emoji.

        see https://discord.com/developers/docs/resources/emoji#delete-guild-emoji
        """

    async def list_application_emojis(
        self,
        *,
        application_id: SnowflakeType,
    ) -> ApplicationEmojis:
        """List application emojis.

        see https://discord.com/developers/docs/resources/emoji#list-application-emojis
        """

    async def get_application_emoji(
        self,
        *,
        application_id: SnowflakeType,
        emoji_id: SnowflakeType,
    ) -> Emoji:
        """Get application emoji.

        see https://discord.com/developers/docs/resources/emoji#get-application-emoji
        """

    async def create_application_emoji(
        self,
        *,
        application_id: SnowflakeType,
        **fields: Unpack[CreateApplicationEmojiParams],
    ) -> Emoji:
        """Create application emoji.

        see https://discord.com/developers/docs/resources/emoji#create-application-emoji
        """

    async def modify_application_emoji(
        self,
        *,
        application_id: SnowflakeType,
        emoji_id: SnowflakeType,
        **fields: Unpack[ModifyApplicationEmojiParams],
    ) -> Emoji:
        """Modify application emoji.

        see https://discord.com/developers/docs/resources/emoji#modify-application-emoji
        """

    async def delete_application_emoji(
        self,
        *,
        application_id: SnowflakeType,
        emoji_id: SnowflakeType,
    ) -> None:
        """Delete application emoji.

        see https://discord.com/developers/docs/resources/emoji#delete-application-emoji
        """

    async def send_soundboard_sound(
        self,
        *,
        channel_id: SnowflakeType,
        **fields: Unpack[SendSoundboardSoundParams],
    ) -> None:
        """Send soundboard sound.

        see https://discord.com/developers/docs/resources/soundboard#send-soundboard-sound
        """

    async def list_default_soundboard_sounds(
        self,
    ) -> ListDefaultSoundboardSoundsResponse:
        """List default soundboard sounds.

        see https://discord.com/developers/docs/resources/soundboard#list-default-soundboard-sounds
        """

    async def list_guild_soundboard_sounds(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> ListGuildSoundboardSoundsResponse:
        """List guild soundboard sounds.

        see https://discord.com/developers/docs/resources/soundboard#list-guild-soundboard-sounds
        """

    async def get_guild_soundboard_sound(
        self,
        *,
        guild_id: SnowflakeType,
        sound_id: SnowflakeType,
    ) -> SoundboardSound:
        """Get guild soundboard sound.

        see https://discord.com/developers/docs/resources/soundboard#get-guild-soundboard-sound
        """

    async def create_guild_soundboard_sound(
        self,
        *,
        guild_id: SnowflakeType,
        **fields: Unpack[CreateGuildSoundboardSoundParams],
    ) -> SoundboardSound:
        """Create guild soundboard sound.

        see https://discord.com/developers/docs/resources/soundboard#create-guild-soundboard-sound
        """

    async def modify_guild_soundboard_sound(
        self,
        *,
        guild_id: SnowflakeType,
        sound_id: SnowflakeType,
        **fields: Unpack[ModifyGuildSoundboardSoundParams],
    ) -> SoundboardSound:
        """Modify guild soundboard sound.

        see https://discord.com/developers/docs/resources/soundboard#modify-guild-soundboard-sound
        """

    async def delete_guild_soundboard_sound(
        self,
        *,
        guild_id: SnowflakeType,
        sound_id: SnowflakeType,
    ) -> None:
        """Delete guild soundboard sound.

        see https://discord.com/developers/docs/resources/soundboard#delete-guild-soundboard-sound
        """

    async def create_lobby(
        self,
        **fields: Unpack[CreateLobbyParams],
    ) -> Lobby:
        """Create lobby.

        see https://discord.com/developers/docs/resources/lobby#create-lobby
        """

    async def get_lobby(
        self,
        *,
        lobby_id: SnowflakeType,
    ) -> Lobby:
        """Get lobby.

        see https://discord.com/developers/docs/resources/lobby#get-lobby
        """

    async def modify_lobby(
        self,
        *,
        lobby_id: SnowflakeType,
        **fields: Unpack[ModifyLobbyParams],
    ) -> Lobby:
        """Modify lobby.

        see https://discord.com/developers/docs/resources/lobby#modify-lobby
        """

    async def delete_lobby(
        self,
        *,
        lobby_id: SnowflakeType,
    ) -> None:
        """Delete lobby.

        see https://discord.com/developers/docs/resources/lobby#delete-lobby
        """

    async def add_lobby_member(
        self,
        *,
        lobby_id: SnowflakeType,
        user_id: SnowflakeType,
        **fields: Unpack[AddLobbyMemberParams],
    ) -> LobbyMember:
        """Add lobby member.

        see https://discord.com/developers/docs/resources/lobby#add-lobby-member
        """

    async def remove_lobby_member(
        self,
        *,
        lobby_id: SnowflakeType,
        user_id: SnowflakeType,
    ) -> None:
        """Remove lobby member.

        see https://discord.com/developers/docs/resources/lobby#remove-lobby-member
        """

    async def leave_lobby(
        self,
        *,
        lobby_id: SnowflakeType,
    ) -> None:
        """Leave lobby.

        see https://discord.com/developers/docs/resources/lobby#leave-lobby
        """

    async def link_channel_to_lobby(
        self,
        *,
        lobby_id: SnowflakeType,
        **fields: Unpack[LinkChannelToLobbyParams],
    ) -> Lobby:
        """Link channel to lobby.

        see https://discord.com/developers/docs/resources/lobby#link-channel-to-lobby
        """

    async def list_entitlements(
        self,
        *,
        application_id: SnowflakeType,
        user_id: SnowflakeType | None = None,
        sku_ids: tuple[SnowflakeType] | None = None,
        before: SnowflakeType | None = None,
        after: SnowflakeType | None = None,
        limit: int | None = None,
        guild_id: SnowflakeType | None = None,
        exclude_ended: bool | None = None,
        exclude_deleted: bool | None = None,
    ) -> list[Entitlement]:
        """List entitlements.

        see https://discord.com/developers/docs/resources/entitlement#list-entitlements
        """

    async def get_entitlement(
        self,
        *,
        application_id: SnowflakeType,
        entitlement_id: SnowflakeType,
    ) -> Entitlement:
        """Get entitlement.

        see https://discord.com/developers/docs/resources/entitlement#get-entitlement
        """

    async def consume_an_entitlement(
        self,
        *,
        application_id: SnowflakeType,
        entitlement_id: SnowflakeType,
    ) -> None:
        """Consume an entitlement.

        see https://discord.com/developers/docs/resources/entitlement#consume-an-entitlement
        """

    async def create_test_entitlement(
        self,
        *,
        application_id: SnowflakeType,
        **fields: Unpack[CreateTestEntitlementParams],
    ) -> Entitlement:
        """Create test entitlement.

        see https://discord.com/developers/docs/resources/entitlement#create-test-entitlement
        """

    async def delete_test_entitlement(
        self,
        *,
        application_id: SnowflakeType,
        entitlement_id: SnowflakeType,
    ) -> None:
        """Delete test entitlement.

        see https://discord.com/developers/docs/resources/entitlement#delete-test-entitlement
        """

    async def create_guild(
        self,
        **fields: Unpack[CreateGuildParams],
    ) -> Guild:
        """https://discord.com/developers/docs/resources/guild"""

    async def get_guild(
        self,
        *,
        guild_id: SnowflakeType,
        with_counts: bool | None = None,
    ) -> Guild:
        """Get guild.

        see https://discord.com/developers/docs/resources/guild#get-guild
        """

    async def get_guild_role_member_counts(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> dict[Snowflake, int]:
        """Get guild role member counts.

        see https://discord.com/developers/docs/resources/guild#get-guild-role-member-counts
        """

    async def get_guild_preview(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> GuildPreview:
        """Get guild preview.

        see https://discord.com/developers/docs/resources/guild#get-guild-preview
        """

    async def modify_guild(
        self,
        *,
        guild_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[ModifyGuildParams],
    ) -> Guild:
        """Modify guild.

        see https://discord.com/developers/docs/resources/guild#modify-guild
        """

    async def modify_guild_incident_actions(
        self,
        *,
        guild_id: SnowflakeType,
        **fields: Unpack[ModifyGuildIncidentActionsParams],
    ) -> GuildIncidentsData:
        """Modify guild incident actions.

        see https://discord.com/developers/docs/resources/guild#modify-guild-incident-actions
        """

    async def delete_guild(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> None:
        """https://discord.com/developers/docs/resources/guild"""

    async def get_guild_channels(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> list[Channel]:
        """Get guild channels.

        see https://discord.com/developers/docs/resources/guild#get-guild-channels
        """

    async def create_guild_channel(
        self,
        *,
        guild_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[CreateGuildChannelParams],
    ) -> Channel:
        """Create guild channel.

        see https://discord.com/developers/docs/resources/guild#create-guild-channel
        """

    async def modify_guild_channel_positions(
        self,
        *,
        guild_id: SnowflakeType,
        channels: list[ModifyGuildChannelPositionParams] | None = None,
        id: SnowflakeType | None = None,
        position: int | None | UnsetType = ...,
        lock_permissions: bool | UnsetType = ...,
        parent_id: SnowflakeType | None | UnsetType = ...,
    ) -> None:
        """Modify guild channel positions.

        see https://discord.com/developers/docs/resources/guild#modify-guild-channel-positions
        """

    async def list_active_guild_threads(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> ListActiveGuildThreadsResponse:
        """List active guild threads.

        see https://discord.com/developers/docs/resources/guild#list-active-guild-threads
        """

    async def get_guild_member(
        self,
        *,
        guild_id: SnowflakeType,
        user_id: SnowflakeType,
    ) -> GuildMember:
        """Get guild member.

        see https://discord.com/developers/docs/resources/guild#get-guild-member
        """

    async def list_guild_members(
        self,
        *,
        guild_id: SnowflakeType,
        limit: int | None = None,
        after: SnowflakeType | None = None,
    ) -> list[GuildMember]:
        """List guild members.

        see https://discord.com/developers/docs/resources/guild#list-guild-members
        """

    async def search_guild_members(
        self,
        *,
        guild_id: SnowflakeType,
        query: str,
        limit: int | None = None,
    ) -> list[GuildMember]:
        """Search guild members.

        see https://discord.com/developers/docs/resources/guild#search-guild-members
        """

    async def add_guild_member(
        self,
        *,
        guild_id: SnowflakeType,
        user_id: SnowflakeType,
        **fields: Unpack[AddGuildMemberParams],
    ) -> GuildMember | None:
        """Add guild member.

        see https://discord.com/developers/docs/resources/guild#add-guild-member
        """

    async def modify_guild_member(
        self,
        *,
        guild_id: SnowflakeType,
        user_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[ModifyGuildMemberParams],
    ) -> GuildMember:
        """Modify guild member.

        see https://discord.com/developers/docs/resources/guild#modify-guild-member
        """

    async def modify_current_member(
        self,
        *,
        guild_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[ModifyCurrentMemberParams],
    ) -> GuildMember:
        """Modify current member.

        see https://discord.com/developers/docs/resources/guild#modify-current-member
        """

    async def modify_current_user_nick(
        self,
        *,
        guild_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[ModifyCurrentUserNickParams],
    ) -> GuildMember:
        """Deprecated in favor of Modify Current Member.

        see https://discord.com/developers/docs/resources/guild#modify-current-user-nick
        """

    async def add_guild_member_role(
        self,
        *,
        guild_id: SnowflakeType,
        user_id: SnowflakeType,
        role_id: SnowflakeType,
        reason: str | None = None,
    ) -> None:
        """Add guild member role.

        see https://discord.com/developers/docs/resources/guild#add-guild-member-role
        """

    async def remove_guild_member_role(
        self,
        *,
        guild_id: SnowflakeType,
        user_id: SnowflakeType,
        role_id: SnowflakeType,
        reason: str | None = None,
    ) -> None:
        """Remove guild member role.

        see https://discord.com/developers/docs/resources/guild#remove-guild-member-role
        """

    async def remove_guild_member(
        self,
        *,
        guild_id: SnowflakeType,
        user_id: SnowflakeType,
        reason: str | None = None,
    ) -> None:
        """Remove guild member.

        see https://discord.com/developers/docs/resources/guild#remove-guild-member
        """

    @overload
    async def get_guild_bans(
        self,
        *,
        guild_id: SnowflakeType,
        limit: int | None = None,
        before: SnowflakeType | None = None,
        after: None = None,
    ) -> list[Ban]: ...
    @overload
    async def get_guild_bans(
        self,
        *,
        guild_id: SnowflakeType,
        limit: int | None = None,
        before: None = None,
        after: SnowflakeType | None = None,
    ) -> list[Ban]: ...
    async def get_guild_ban(
        self,
        *,
        guild_id: SnowflakeType,
        user_id: SnowflakeType,
    ) -> Ban:
        """Get guild ban.

        see https://discord.com/developers/docs/resources/guild#get-guild-ban
        """

    @overload
    async def create_guild_ban(
        self,
        *,
        guild_id: SnowflakeType,
        user_id: SnowflakeType,
        delete_message_days: int = ...,
        reason: str | None = None,
    ) -> None: ...
    @overload
    async def create_guild_ban(
        self,
        *,
        guild_id: SnowflakeType,
        user_id: SnowflakeType,
        delete_message_seconds: int = ...,
        reason: str | None = None,
    ) -> None: ...
    async def remove_guild_ban(
        self,
        *,
        guild_id: SnowflakeType,
        user_id: SnowflakeType,
        reason: str | None = None,
    ) -> None:
        """Remove guild ban.

        see https://discord.com/developers/docs/resources/guild#remove-guild-ban
        """

    async def bulk_guild_ban(
        self,
        *,
        guild_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[BulkGuildBanParams],
    ) -> BulkBan:
        """Bulk guild ban.

        see https://discord.com/developers/docs/resources/guild#bulk-guild-ban
        """

    async def get_guild_roles(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> list[Role]:
        """Get guild roles.

        see https://discord.com/developers/docs/resources/guild#get-guild-roles
        """

    async def get_guild_role(
        self,
        *,
        guild_id: SnowflakeType,
        role_id: SnowflakeType,
    ) -> Role:
        """Get guild role.

        see https://discord.com/developers/docs/resources/guild#get-guild-role
        """

    async def create_guild_role(
        self,
        *,
        guild_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[CreateGuildRoleParams],
    ) -> Role:
        """Create guild role.

        see https://discord.com/developers/docs/resources/guild#create-guild-role
        """

    async def modify_guild_role_positions(
        self,
        *,
        guild_id: SnowflakeType,
        roles: list[ModifyGuildRolePositionParams] | None = None,
        id: SnowflakeType | None = None,
        position: int | None | UnsetType = ...,
        reason: str | None = None,
    ) -> list[Role]:
        """Modify guild role positions.

        see https://discord.com/developers/docs/resources/guild#modify-guild-role-positions
        """

    async def modify_guild_role(
        self,
        *,
        guild_id: SnowflakeType,
        role_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[ModifyGuildRoleParams],
    ) -> Role:
        """Modify guild role.

        see https://discord.com/developers/docs/resources/guild#modify-guild-role
        """

    async def modify_guild_MFA_level(
        self,
        *,
        guild_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[ModifyGuildMFAParams],
    ) -> None:
        """https://discord.com/developers/docs/resources/guild"""

    async def delete_guild_role(
        self,
        *,
        guild_id: SnowflakeType,
        role_id: SnowflakeType,
        reason: str | None = None,
    ) -> None:
        """Delete guild role.

        see https://discord.com/developers/docs/resources/guild#delete-guild-role
        """

    async def get_guild_prune_count(
        self,
        *,
        guild_id: SnowflakeType,
        days: int | None = None,
        include_roles: list[SnowflakeType] | None = None,
    ) -> dict[Literal["pruned"], int]:
        """Get guild prune count.

        see https://discord.com/developers/docs/resources/guild#get-guild-prune-count
        """

    async def begin_guild_prune(
        self,
        *,
        guild_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[BeginGuildPruneParams],
    ) -> dict[Literal["pruned"], int]:
        """Begin guild prune.

        see https://discord.com/developers/docs/resources/guild#begin-guild-prune
        """

    async def get_guild_voice_regions(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> list[VoiceRegion]:
        """Get guild voice regions.

        see https://discord.com/developers/docs/resources/guild#get-guild-voice-regions
        """

    async def get_guild_invites(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> list[Invite]:
        """Get guild invites.

        see https://discord.com/developers/docs/resources/guild#get-guild-invites
        """

    async def get_guild_integrations(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> list[Integration]:
        """Get guild integrations.

        see https://discord.com/developers/docs/resources/guild#get-guild-integrations
        """

    async def delete_guild_integration(
        self,
        *,
        guild_id: SnowflakeType,
        integration_id: SnowflakeType,
        reason: str | None = None,
    ) -> None:
        """Delete guild integration.

        see https://discord.com/developers/docs/resources/guild#delete-guild-integration
        """

    async def get_guild_widget_settings(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> GuildWidgetSettings:
        """Get guild widget settings.

        see https://discord.com/developers/docs/resources/guild#get-guild-widget-settings
        """

    async def modify_guild_widget(
        self,
        *,
        guild_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[ModifyGuildWidgetParams],
    ) -> GuildWidgetSettings:
        """Modify guild widget.

        see https://discord.com/developers/docs/resources/guild#modify-guild-widget
        """

    async def get_guild_widget(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> GuildWidget:
        """Get guild widget.

        see https://discord.com/developers/docs/resources/guild#get-guild-widget
        """

    async def get_guild_vanity_url(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> GuildVanityURL:
        """Get guild vanity URL.

        see https://discord.com/developers/docs/resources/guild#get-guild-vanity-url
        """

    async def get_guild_widget_image(
        self,
        *,
        guild_id: SnowflakeType,
        style: Literal["shield", "banner1", "banner2", "banner3", "banner4"]
        | None = None,
    ) -> bytes:
        """Get guild widget image.

        see https://discord.com/developers/docs/resources/guild#get-guild-widget-image
        """

    async def get_guild_welcome_screen(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> WelcomeScreen:
        """Get guild welcome screen.

        see https://discord.com/developers/docs/resources/guild#get-guild-welcome-screen
        """

    async def modify_guild_welcome_screen(
        self,
        *,
        guild_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[ModifyGuildWelcomeScreenParams],
    ) -> WelcomeScreen:
        """Modify guild welcome screen.

        see https://discord.com/developers/docs/resources/guild#modify-guild-welcome-screen
        """

    async def get_guild_onboarding(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> GuildOnboarding:
        """Get guild onboarding.

        see https://discord.com/developers/docs/resources/guild#get-guild-onboarding
        """

    async def modify_guild_onboarding(
        self,
        *,
        guild_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[ModifyGuildOnboardingParams],
    ) -> GuildOnboarding:
        """Modify guild onboarding.

        see https://discord.com/developers/docs/resources/guild#modify-guild-onboarding
        """

    async def list_voice_regions(
        self,
    ) -> list[VoiceRegion]:
        """List voice regions.

        see https://discord.com/developers/docs/resources/voice#list-voice-regions
        """

    async def get_current_user_voice_state(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> VoiceState:
        """Get current user voice state.

        see https://discord.com/developers/docs/resources/voice#get-current-user-voice-state
        """

    async def get_user_voice_state(
        self,
        *,
        guild_id: SnowflakeType,
        user_id: SnowflakeType,
    ) -> VoiceState:
        """Get user voice state.

        see https://discord.com/developers/docs/resources/voice#get-user-voice-state
        """

    async def modify_current_user_voice_state(
        self,
        *,
        guild_id: SnowflakeType,
        **fields: Unpack[ModifyCurrentUserVoiceStateParams],
    ) -> None:
        """Modify current user voice state.

        see https://discord.com/developers/docs/resources/voice#modify-current-user-voice-state
        """

    async def modify_user_voice_state(
        self,
        *,
        guild_id: SnowflakeType,
        user_id: SnowflakeType,
        **fields: Unpack[ModifyUserVoiceStateParams],
    ) -> None:
        """Modify user voice state.

        see https://discord.com/developers/docs/resources/voice#modify-user-voice-state
        """

    async def list_scheduled_events_for_guild(
        self,
        *,
        guild_id: SnowflakeType,
        with_user_count: bool | None = None,
    ) -> list[GuildScheduledEvent]:
        """List scheduled events for guild.

        see https://discord.com/developers/docs/resources/guild-scheduled-event#list-scheduled-events-for-guild
        """

    async def create_guild_schedule_event(
        self,
        *,
        guild_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[CreateGuildScheduledEventParams],
    ) -> GuildScheduledEvent:
        """Create guild scheduled event.

        see https://discord.com/developers/docs/resources/guild-scheduled-event#create-guild-scheduled-event
        """

    async def get_guild_scheduled_event(
        self,
        *,
        guild_id: SnowflakeType,
        event_id: SnowflakeType,
        with_user_count: bool | None = None,
    ) -> GuildScheduledEvent:
        """Get guild scheduled event.

        see https://discord.com/developers/docs/resources/guild-scheduled-event#get-guild-scheduled-event
        """

    async def modify_guild_scheduled_event(
        self,
        *,
        guild_id: SnowflakeType,
        event_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[ModifyGuildScheduledEventParams],
    ) -> GuildScheduledEvent:
        """Modify guild scheduled event.

        see https://discord.com/developers/docs/resources/guild-scheduled-event#modify-guild-scheduled-event
        """

    async def delete_guild_scheduled_event(
        self,
        *,
        guild_id: SnowflakeType,
        event_id: SnowflakeType,
    ) -> None:
        """Delete guild scheduled event.

        see https://discord.com/developers/docs/resources/guild-scheduled-event#delete-guild-scheduled-event
        """

    async def get_guild_scheduled_event_users(
        self,
        *,
        guild_id: SnowflakeType,
        event_id: SnowflakeType,
        limit: int | None = None,
        with_member: bool | None = None,
        before: SnowflakeType | None = None,
        after: SnowflakeType | None = None,
    ) -> list[GuildScheduledEventUser]:
        """Get guild scheduled event users.

        see https://discord.com/developers/docs/resources/guild-scheduled-event#get-guild-scheduled-event-users
        """

    async def get_guild_template(
        self,
        *,
        template_code: str,
    ) -> GuildTemplate:
        """Get guild template.

        see https://discord.com/developers/docs/resources/guild-template#get-guild-template
        """

    async def create_guild_from_guild_template(
        self,
        *,
        template_code: str,
        name: str,
        icon: str | None = None,
    ) -> Guild:
        """https://discord.com/developers/docs/resources/guild-template"""

    async def get_guild_templates(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> list[GuildTemplate]:
        """Get guild templates.

        see https://discord.com/developers/docs/resources/guild-template#get-guild-templates
        """

    async def create_guild_template(
        self,
        *,
        guild_id: SnowflakeType,
        **fields: Unpack[CreateGuildTemplateParams],
    ) -> GuildTemplate:
        """Create guild template.

        see https://discord.com/developers/docs/resources/guild-template#create-guild-template
        """

    async def sync_guild_template(
        self,
        *,
        guild_id: SnowflakeType,
        template_code: str,
    ) -> GuildTemplate:
        """Sync guild template.

        see https://discord.com/developers/docs/resources/guild-template#sync-guild-template
        """

    async def modify_guild_template(
        self,
        *,
        guild_id: SnowflakeType,
        template_code: str,
        **fields: Unpack[ModifyGuildTemplateParams],
    ) -> GuildTemplate:
        """Modify guild template.

        see https://discord.com/developers/docs/resources/guild-template#modify-guild-template
        """

    async def delete_guild_template(
        self,
        *,
        guild_id: SnowflakeType,
        template_code: str,
    ) -> GuildTemplate:
        """Delete guild template.

        see https://discord.com/developers/docs/resources/guild-template#delete-guild-template
        """

    async def get_invite(
        self,
        *,
        invite_code: str,
        with_counts: bool | None = None,
        with_expiration: bool | None = None,
        guild_scheduled_event_id: SnowflakeType | None = None,
    ) -> Invite:
        """Get invite.

        see https://discord.com/developers/docs/resources/invite#get-invite
        """

    async def delete_invite(
        self,
        *,
        invite_code: str,
        reason: str | None = None,
    ) -> Invite:
        """Delete invite.

        see https://discord.com/developers/docs/resources/invite#delete-invite
        """

    async def get_invite_target_users(
        self,
        *,
        invite_code: str,
    ) -> bytes:
        """Get invite target users.

        see https://discord.com/developers/docs/resources/invite#get-target-users
        """

    async def update_invite_target_users(
        self,
        *,
        invite_code: str,
        target_users_file: File,
    ) -> None:
        """Update invite target users.

        see https://discord.com/developers/docs/resources/invite#update-target-users
        """

    async def get_invite_target_users_job_status(
        self,
        *,
        invite_code: str,
    ) -> InviteTargetUsersJobStatus:
        """Get invite target users job status.

        see https://discord.com/developers/docs/resources/invite#get-target-users-job-status
        """

    async def get_answer_voters(
        self,
        *,
        channel_id: SnowflakeType,
        message_id: SnowflakeType,
        answer_id: int,
        after: SnowflakeType | None = None,
        limit: int | None = None,
    ) -> AnswerVoters:
        """Get answer voters.

        see https://discord.com/developers/docs/resources/poll#get-answer-voters
        """

    async def end_poll(
        self,
        *,
        channel_id: SnowflakeType,
        message_id: SnowflakeType,
    ) -> MessageGet:
        """End poll.

        see https://discord.com/developers/docs/resources/poll#end-poll
        """

    async def list_SKUs(
        self,
        *,
        application_id: SnowflakeType,
    ) -> list[SKU]:
        """List SKUs.

        see https://discord.com/developers/docs/resources/sku#list-skus
        """

    async def create_stage_instance(
        self,
        *,
        reason: str | None = None,
        **fields: Unpack[CreateStageInstanceParams],
    ) -> StageInstance:
        """Create stage instance.

        see https://discord.com/developers/docs/resources/stage-instance#create-stage-instance
        """

    async def get_stage_instance(
        self,
        *,
        channel_id: SnowflakeType,
    ) -> StageInstance:
        """Get stage instance.

        see https://discord.com/developers/docs/resources/stage-instance#get-stage-instance
        """

    async def modify_stage_instance(
        self,
        *,
        channel_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[ModifyStageInstanceParams],
    ) -> StageInstance:
        """Modify stage instance.

        see https://discord.com/developers/docs/resources/stage-instance#modify-stage-instance
        """

    async def delete_stage_instance(
        self,
        *,
        channel_id: SnowflakeType,
        reason: str | None = None,
    ) -> None:
        """Delete stage instance.

        see https://discord.com/developers/docs/resources/stage-instance#delete-stage-instance
        """

    async def get_sticker(
        self,
        *,
        sticker_id: SnowflakeType,
    ) -> Sticker:
        """Get sticker.

        see https://discord.com/developers/docs/resources/sticker#get-sticker
        """

    async def list_nitro_sticker_packs(
        self,
    ) -> StickerPacksResponse:
        """List sticker packs.

        see https://discord.com/developers/docs/resources/sticker#list-sticker-packs
        """

    async def get_sticker_packs(
        self,
        *,
        pack_id: SnowflakeType,
    ) -> StickerPack:
        """Get sticker pack.

        see https://discord.com/developers/docs/resources/sticker#get-sticker-pack
        """

    async def list_guild_stickers(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> list[Sticker]:
        """List guild stickers.

        see https://discord.com/developers/docs/resources/sticker#list-guild-stickers
        """

    async def get_guild_sticker(
        self,
        *,
        guild_id: SnowflakeType,
        sticker_id: SnowflakeType,
    ) -> Sticker:
        """Get guild sticker.

        see https://discord.com/developers/docs/resources/sticker#get-guild-sticker
        """

    async def create_guild_sticker(
        self,
        *,
        guild_id: SnowflakeType,
        name: str,
        description: str,
        tags: str,
        file: File,
        reason: str | None = None,
    ) -> Sticker:
        """Create guild sticker.

        see https://discord.com/developers/docs/resources/sticker#create-guild-sticker
        """

    async def modify_guild_sticker(
        self,
        *,
        guild_id: SnowflakeType,
        sticker_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[ModifyGuildStickerParams],
    ) -> Sticker:
        """Modify guild sticker.

        see https://discord.com/developers/docs/resources/sticker#modify-guild-sticker
        """

    async def delete_guild_sticker(
        self,
        *,
        guild_id: SnowflakeType,
        sticker_id: SnowflakeType,
        reason: str | None = None,
    ) -> None:
        """Delete guild sticker.

        see https://discord.com/developers/docs/resources/sticker#delete-guild-sticker
        """

    async def list_SKU_subscriptions(
        self,
        *,
        sku_id: SnowflakeType,
        before: SnowflakeType | None = None,
        after: SnowflakeType | None = None,
        limit: int | None = None,
        user_id: SnowflakeType | None = None,
    ) -> list[Subscription]:
        """List SKU subscriptions.

        see https://discord.com/developers/docs/resources/subscription#list-sku-subscriptions
        """

    async def get_SKU_subscription(
        self,
        *,
        sku_id: SnowflakeType,
        subscription_id: SnowflakeType,
    ) -> Subscription:
        """Get SKU subscription.

        see https://discord.com/developers/docs/resources/subscription#get-sku-subscription
        """

    async def get_current_user(
        self,
    ) -> User:
        """Get current user.

        see https://discord.com/developers/docs/resources/user#get-current-user
        """

    async def get_user(
        self,
        *,
        user_id: SnowflakeType,
    ) -> User:
        """Get user.

        see https://discord.com/developers/docs/resources/user#get-user
        """

    async def modify_current_user(
        self,
        **fields: Unpack[ModifyCurrentUserParams],
    ) -> User:
        """Modify current user.

        see https://discord.com/developers/docs/resources/user#modify-current-user
        """

    async def get_current_user_guilds(
        self,
        *,
        before: SnowflakeType | None = None,
        after: SnowflakeType | None = None,
        limit: int | None = None,
        with_counts: bool | None = None,
    ) -> list[CurrentUserGuild]:
        """Get current user guilds.

        see https://discord.com/developers/docs/resources/user#get-current-user-guilds
        """

    async def get_current_user_guild_member(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> GuildMember:
        """Get current user guild member.

        see https://discord.com/developers/docs/resources/user#get-current-user-guild-member
        """

    async def leave_guild(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> None:
        """Leave guild.

        see https://discord.com/developers/docs/resources/user#leave-guild
        """

    async def create_DM(
        self,
        **fields: Unpack[CreateDMParams],
    ) -> Channel:
        """Create DM.

        see https://discord.com/developers/docs/resources/user#create-dm
        """

    async def create_group_DM(
        self,
        **fields: Unpack[CreateGroupDMParams],
    ) -> Channel:
        """Create group DM.

        see https://discord.com/developers/docs/resources/user#create-group-dm
        """

    async def get_user_connections(
        self,
        *,
        access_token: str,
    ) -> list[Connection]:
        """Get current user connections.

        see https://discord.com/developers/docs/resources/user#get-current-user-connections
        """

    async def get_user_application_role_connection(
        self,
        *,
        application_id: SnowflakeType,
        access_token: str,
    ) -> ApplicationRoleConnection:
        """Get current user application role connection.

        see https://discord.com/developers/docs/resources/user#get-current-user-application-role-connection
        """

    async def update_user_application_role_connection(
        self,
        *,
        application_id: SnowflakeType,
        access_token: str,
        **fields: Unpack[UpdateUserApplicationRoleConnectionParams],
    ) -> ApplicationRoleConnection:
        """Update current user application role connection.

        see https://discord.com/developers/docs/resources/user#update-current-user-application-role-connection
        """

    async def create_webhook(
        self,
        *,
        channel_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[CreateWebhookParams],
    ) -> Webhook:
        """Create webhook.

        see https://discord.com/developers/docs/resources/webhook#create-webhook
        """

    async def get_channel_webhooks(
        self,
        *,
        channel_id: SnowflakeType,
    ) -> list[Webhook]:
        """Get channel webhooks.

        see https://discord.com/developers/docs/resources/webhook#get-channel-webhooks
        """

    async def get_guild_webhooks(
        self,
        *,
        guild_id: SnowflakeType,
    ) -> list[Webhook]:
        """Get guild webhooks.

        see https://discord.com/developers/docs/resources/webhook#get-guild-webhooks
        """

    async def get_webhook(
        self,
        *,
        webhook_id: SnowflakeType,
    ) -> Webhook:
        """Get webhook.

        see https://discord.com/developers/docs/resources/webhook#get-webhook
        """

    async def get_webhook_with_token(
        self,
        *,
        webhook_id: SnowflakeType,
        token: str,
    ) -> Webhook:
        """Get webhook with token.

        see https://discord.com/developers/docs/resources/webhook#get-webhook-with-token
        """

    async def modify_webhook(
        self,
        *,
        webhook_id: SnowflakeType,
        reason: str | None = None,
        **fields: Unpack[ModifyWebhookParams],
    ) -> Webhook:
        """Modify webhook.

        see https://discord.com/developers/docs/resources/webhook#modify-webhook
        """

    async def modify_webhook_with_token(
        self,
        *,
        webhook_id: SnowflakeType,
        token: str,
        **fields: Unpack[ModifyWebhookParams],
    ) -> Webhook:
        """Modify webhook with token.

        see https://discord.com/developers/docs/resources/webhook#modify-webhook-with-token
        """

    async def delete_webhook(
        self,
        *,
        webhook_id: SnowflakeType,
        reason: str | None = None,
    ) -> None:
        """Delete webhook.

        see https://discord.com/developers/docs/resources/webhook#delete-webhook
        """

    async def delete_webhook_with_token(
        self,
        *,
        webhook_id: SnowflakeType,
        token: str,
    ) -> None:
        """Delete webhook with token.

        see https://discord.com/developers/docs/resources/webhook#delete-webhook-with-token
        """

    @overload
    async def execute_webhook(
        self,
        *,
        webhook_id: SnowflakeType,
        token: str,
        wait: Literal[True],
        thread_id: SnowflakeType | None = None,
        with_components: bool | None = None,
        **fields: Unpack[ExecuteWebhookParams],
    ) -> MessageGet: ...
    @overload
    async def execute_webhook(
        self,
        *,
        webhook_id: SnowflakeType,
        token: str,
        wait: Literal[False] | None = None,
        thread_id: SnowflakeType | None = None,
        with_components: bool | None = None,
        **fields: Unpack[ExecuteWebhookParams],
    ) -> None: ...
    async def execute_slack_compatible_webhook(
        self,
        *,
        webhook_id: SnowflakeType,
        token: str,
        payload: dict[str, Any],
        thread_id: SnowflakeType | None = None,
        wait: bool | None = None,
    ) -> MessageGet | None:
        """Execute Slack-compatible webhook.

        see https://discord.com/developers/docs/resources/webhook#execute-slack-compatible-webhook
        """

    async def execute_github_compatible_webhook(
        self,
        *,
        webhook_id: SnowflakeType,
        token: str,
        payload: dict[str, Any],
        thread_id: SnowflakeType | None = None,
        wait: bool | None = None,
    ) -> MessageGet | None:
        """Execute GitHub-compatible webhook.

        see https://discord.com/developers/docs/resources/webhook#execute-github-compatible-webhook
        """

    async def get_webhook_message(
        self,
        *,
        webhook_id: SnowflakeType,
        token: str,
        message_id: SnowflakeType,
        thread_id: SnowflakeType | None = None,
    ) -> MessageGet:
        """Get webhook message.

        see https://discord.com/developers/docs/resources/webhook#get-webhook-message
        """

    async def edit_webhook_message(
        self,
        *,
        webhook_id: SnowflakeType,
        webhook_token: str,
        message_id: SnowflakeType,
        thread_id: SnowflakeType | None = None,
        with_components: bool | None = None,
        **fields: Unpack[WebhookMessageEditParams],
    ) -> MessageGet:
        """Edit webhook message.

        see https://discord.com/developers/docs/resources/webhook#edit-webhook-message
        """

    async def delete_webhook_message(
        self,
        *,
        webhook_id: SnowflakeType,
        token: str,
        message_id: SnowflakeType,
        thread_id: SnowflakeType | None = None,
    ) -> None:
        """Delete webhook message.

        see https://discord.com/developers/docs/resources/webhook#delete-webhook-message
        """

    async def get_gateway(
        self,
    ) -> Gateway:
        """Get gateway.

        see https://discord.com/developers/docs/events/gateway#get-gateway
        """

    async def get_gateway_bot(
        self,
    ) -> GatewayBot:
        """Get gateway bot.

        see https://discord.com/developers/docs/events/gateway#get-gateway-bot
        """

    async def get_current_bot_application_information(
        self,
    ) -> Application:
        """Get current bot application information.

        see https://discord.com/developers/docs/topics/oauth2#get-current-bot-application-information
        """

    async def get_current_authorization_information(
        self,
        *,
        access_token: str,
    ) -> AuthorizationResponse:
        """Get current authorization information.

        see https://discord.com/developers/docs/topics/oauth2#get-current-authorization-information
        """
