"""Canonical Discord domain ownership manifests."""

from __future__ import annotations

DOMAIN_TYPE_MODULES: tuple[str, ...] = (
    "nonebot.adapters.discord.domains.command.types",
    "nonebot.adapters.discord.domains.component.types",
    "nonebot.adapters.discord.domains.interaction.types",
    "nonebot.adapters.discord.domains.application.types",
    "nonebot.adapters.discord.domains.moderation.types",
    "nonebot.adapters.discord.domains.channel.types",
    "nonebot.adapters.discord.domains.message.types",
    "nonebot.adapters.discord.domains.guild.types",
    "nonebot.adapters.discord.domains.invite.types",
    "nonebot.adapters.discord.domains.voice.types",
    "nonebot.adapters.discord.domains.sticker.types",
    "nonebot.adapters.discord.domains.user.types",
    "nonebot.adapters.discord.domains.webhook.types",
    "nonebot.adapters.discord.domains.lobby.types",
    "nonebot.adapters.discord.domains.gateway.types",
)

PROTOCOL_TYPE_EXPORTS: tuple[str, ...] = ("UNSET", "Missing", "MissingOrNullable")

TYPE_EXPORT_OWNERS: dict[str, str] = {
    "ActivityAssetImage": "gateway",
    "ActivityFlags": "gateway",
    "ActivityType": "gateway",
    "AllowedMentionType": "message",
    "AnimationType": "voice",
    "ApplicationCommandOptionType": "command",
    "ApplicationCommandPermissionsType": "command",
    "ApplicationCommandType": "command",
    "ApplicationFlag": "application",
    "ApplicationIntegrationType": "application",
    "ApplicationRoleConnectionMetadataType": "application",
    "AttachmentFlag": "message",
    "AuditLogEventType": "moderation",
    "AutoModerationActionType": "moderation",
    "AutoModerationRuleEventType": "moderation",
    "ButtonStyle": "component",
    "ChannelFlags": "channel",
    "ChannelType": "channel",
    "ComponentType": "component",
    "ConnectionServiceType": "user",
    "DefaultMessageNotificationLevel": "guild",
    "EmbedTypes": "message",
    "EntitlementType": "application",
    "ExplicitContentFilterLevel": "guild",
    "ForumLayoutTypes": "channel",
    "GuildFeature": "guild",
    "GuildMemberFlags": "guild",
    "GuildNSFWLevel": "guild",
    "GuildScheduledEventEntityType": "guild",
    "GuildScheduledEventPrivacyLevel": "guild",
    "GuildScheduledEventRecurrenceRuleFrequency": "guild",
    "GuildScheduledEventRecurrenceRuleMonth": "guild",
    "GuildScheduledEventRecurrenceRuleWeekday": "guild",
    "GuildScheduledEventStatus": "guild",
    "IntegrationExpireBehaviors": "guild",
    "InteractionCallbackType": "interaction",
    "InteractionContextType": "interaction",
    "InteractionType": "interaction",
    "InviteTargetType": "invite",
    "InviteType": "invite",
    "KeywordPresetType": "moderation",
    "LobbyMemberFlags": "lobby",
    "MFALevel": "guild",
    "MembershipState": "application",
    "MessageActivityType": "message",
    "MessageFlag": "message",
    "MessageReferenceType": "message",
    "MessageType": "message",
    "MutableGuildFeature": "guild",
    "OnboardingMode": "guild",
    "OnboardingPromptType": "guild",
    "OverwriteType": "channel",
    "PremiumTier": "guild",
    "PremiumType": "user",
    "PresenceStatus": "gateway",
    "ReactionType": "message",
    "RoleFlag": "guild",
    "SKUFlag": "application",
    "SKUType": "application",
    "SortOrderTypes": "channel",
    "StagePrivacyLevel": "voice",
    "StickerFormatType": "sticker",
    "StickerType": "sticker",
    "SubscriptionStatus": "application",
    "SystemChannelFlags": "guild",
    "TeamMemberRoleType": "application",
    "TextInputStyle": "component",
    "TimeStampStyle": "message",
    "TriggerType": "moderation",
    "UpdatePresenceStatusType": "gateway",
    "UserFlags": "user",
    "VerificationLevel": "guild",
    "VideoQualityMode": "channel",
    "VisibilityType": "user",
    "WebhookType": "webhook",
}

DOMAIN_MODEL_MODULES: tuple[str, ...] = (
    "nonebot.adapters.discord.domains.command.read",
    "nonebot.adapters.discord.domains.command.write",
    "nonebot.adapters.discord.domains.component.read",
    "nonebot.adapters.discord.domains.component.write",
    "nonebot.adapters.discord.domains.application.read",
    "nonebot.adapters.discord.domains.application.write",
    "nonebot.adapters.discord.domains.application.gateway",
    "nonebot.adapters.discord.domains.moderation.read",
    "nonebot.adapters.discord.domains.moderation.write",
    "nonebot.adapters.discord.domains.moderation.gateway",
    "nonebot.adapters.discord.domains.channel.read",
    "nonebot.adapters.discord.domains.channel.write",
    "nonebot.adapters.discord.domains.channel.gateway",
    "nonebot.adapters.discord.domains.message.read",
    "nonebot.adapters.discord.domains.message.write",
    "nonebot.adapters.discord.domains.message.gateway",
    "nonebot.adapters.discord.domains.interaction.read",
    "nonebot.adapters.discord.domains.interaction.write",
    "nonebot.adapters.discord.domains.interaction.gateway",
    "nonebot.adapters.discord.domains.emoji.read",
    "nonebot.adapters.discord.domains.emoji.write",
    "nonebot.adapters.discord.domains.guild.read",
    "nonebot.adapters.discord.domains.guild.write",
    "nonebot.adapters.discord.domains.guild.gateway",
    "nonebot.adapters.discord.domains.invite.read",
    "nonebot.adapters.discord.domains.invite.gateway",
    "nonebot.adapters.discord.domains.voice.read",
    "nonebot.adapters.discord.domains.voice.write",
    "nonebot.adapters.discord.domains.voice.gateway",
    "nonebot.adapters.discord.domains.sticker.read",
    "nonebot.adapters.discord.domains.sticker.write",
    "nonebot.adapters.discord.domains.user.read",
    "nonebot.adapters.discord.domains.user.write",
    "nonebot.adapters.discord.domains.user.gateway",
    "nonebot.adapters.discord.domains.webhook.read",
    "nonebot.adapters.discord.domains.webhook.write",
    "nonebot.adapters.discord.domains.webhook.gateway",
    "nonebot.adapters.discord.domains.soundboard.read",
    "nonebot.adapters.discord.domains.soundboard.write",
    "nonebot.adapters.discord.domains.soundboard.gateway",
    "nonebot.adapters.discord.domains.lobby.read",
    "nonebot.adapters.discord.domains.lobby.write",
    "nonebot.adapters.discord.domains.gateway.read",
    "nonebot.adapters.discord.domains.gateway.write",
)

__all__ = [
    "DOMAIN_MODEL_MODULES",
    "DOMAIN_TYPE_MODULES",
    "PROTOCOL_TYPE_EXPORTS",
    "TYPE_EXPORT_OWNERS",
]
