"""Private common imports for canonical Discord domain models."""

from __future__ import annotations

import datetime
from typing import TYPE_CHECKING, Any, Generic, Literal, TypeVar
import warnings

from nonebot.compat import PYDANTIC_V2
from pydantic import BaseModel, Field

if PYDANTIC_V2 or TYPE_CHECKING:
    GenericModel = BaseModel
else:
    from pydantic.generics import GenericModel

from ._types import (
    ActivityAssetImage,
    ActivityFlags,
    ActivityType,
    AllowedMentionType,
    AnimationType,
    ApplicationCommandOptionType,
    ApplicationCommandPermissionsType,
    ApplicationCommandType,
    ApplicationFlag,
    ApplicationIntegrationType,
    ApplicationRoleConnectionMetadataType,
    AttachmentFlag,
    AuditLogEventType,
    AutoModerationActionType,
    AutoModerationRuleEventType,
    ButtonStyle,
    ChannelFlags,
    ChannelType,
    ComponentType,
    ConnectionServiceType,
    DefaultMessageNotificationLevel,
    EmbedTypes,
    EntitlementType,
    ExplicitContentFilterLevel,
    ForumLayoutTypes,
    GuildFeature,
    GuildMemberFlags,
    GuildNSFWLevel,
    GuildScheduledEventEntityType,
    GuildScheduledEventPrivacyLevel,
    GuildScheduledEventRecurrenceRuleFrequency,
    GuildScheduledEventRecurrenceRuleMonth,
    GuildScheduledEventRecurrenceRuleWeekday,
    GuildScheduledEventStatus,
    IntegrationExpireBehaviors,
    InteractionCallbackType,
    InteractionContextType,
    InteractionType,
    InviteTargetType,
    InviteType,
    KeywordPresetType,
    LobbyMemberFlags,
    MembershipState,
    MessageActivityType,
    MessageFlag,
    MessageReferenceType,
    MessageType,
    MFALevel,
    MutableGuildFeature,
    OnboardingMode,
    OnboardingPromptType,
    OverwriteType,
    PremiumTier,
    PremiumType,
    PresenceStatus,
    ReactionType,
    RoleFlag,
    SKUFlag,
    SKUType,
    SortOrderTypes,
    StagePrivacyLevel,
    StickerFormatType,
    StickerType,
    SubscriptionStatus,
    SystemChannelFlags,
    TeamMemberRoleType,
    TextInputStyle,
    TimeStampStyle,
    TriggerType,
    UpdatePresenceStatusType,
    UserFlags,
    VerificationLevel,
    VideoQualityMode,
    VisibilityType,
    WebhookType,
)
from ..protocol import (
    UNSET,
    Missing,
    MissingOrNullable,
    Snowflake,
    SnowflakeType,
    UnsetType,
    is_not_unset,
    is_unset,
)

T = TypeVar("T", str, int, float)

__all__ = [
    "PYDANTIC_V2",
    "TYPE_CHECKING",
    "UNSET",
    "UNSET",
    "ActivityAssetImage",
    "ActivityFlags",
    "ActivityType",
    "AllowedMentionType",
    "AnimationType",
    "Any",
    "ApplicationCommandOptionType",
    "ApplicationCommandPermissionsType",
    "ApplicationCommandType",
    "ApplicationFlag",
    "ApplicationIntegrationType",
    "ApplicationRoleConnectionMetadataType",
    "AttachmentFlag",
    "AuditLogEventType",
    "AutoModerationActionType",
    "AutoModerationRuleEventType",
    "BaseModel",
    "ButtonStyle",
    "ChannelFlags",
    "ChannelType",
    "ComponentType",
    "ConnectionServiceType",
    "DefaultMessageNotificationLevel",
    "EmbedTypes",
    "EntitlementType",
    "ExplicitContentFilterLevel",
    "Field",
    "ForumLayoutTypes",
    "Generic",
    "GenericModel",
    "GuildFeature",
    "GuildMemberFlags",
    "GuildNSFWLevel",
    "GuildScheduledEventEntityType",
    "GuildScheduledEventPrivacyLevel",
    "GuildScheduledEventRecurrenceRuleFrequency",
    "GuildScheduledEventRecurrenceRuleMonth",
    "GuildScheduledEventRecurrenceRuleWeekday",
    "GuildScheduledEventStatus",
    "IntegrationExpireBehaviors",
    "InteractionCallbackType",
    "InteractionContextType",
    "InteractionType",
    "InviteTargetType",
    "InviteType",
    "KeywordPresetType",
    "Literal",
    "LobbyMemberFlags",
    "MFALevel",
    "MembershipState",
    "MessageActivityType",
    "MessageFlag",
    "MessageReferenceType",
    "MessageType",
    "Missing",
    "Missing",
    "MissingOrNullable",
    "MissingOrNullable",
    "MutableGuildFeature",
    "OnboardingMode",
    "OnboardingPromptType",
    "OverwriteType",
    "PremiumTier",
    "PremiumType",
    "PresenceStatus",
    "ReactionType",
    "RoleFlag",
    "SKUFlag",
    "SKUType",
    "Snowflake",
    "SnowflakeType",
    "SortOrderTypes",
    "StagePrivacyLevel",
    "StickerFormatType",
    "StickerType",
    "SubscriptionStatus",
    "SystemChannelFlags",
    "T",
    "TeamMemberRoleType",
    "TextInputStyle",
    "TimeStampStyle",
    "TriggerType",
    "TypeVar",
    "UnsetType",
    "UpdatePresenceStatusType",
    "UserFlags",
    "VerificationLevel",
    "VideoQualityMode",
    "VisibilityType",
    "WebhookType",
    "datetime",
    "is_not_unset",
    "is_unset",
    "warnings",
]
