from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .application import (
        ActivityInstance,
        ActivityLocation,
        Application,
        ApplicationIntegrationTypeConfiguration,
        ApplicationRoleConnectionMetadata,
        EditCurrentApplicationParams,
        InstallParams,
    )
    from .audit_log import (
        AuditLog,
        AuditLogChange,
        AuditLogChangeException,
        AuditLogEntry,
        OptionalAuditEntryInfo,
    )
    from .auto_moderation import (
        AutoModerationAction,
        AutoModerationActionExecution,
        AutoModerationActionMetadata,
        AutoModerationRule,
        AutoModerationRuleCreate,
        AutoModerationRuleDelete,
        AutoModerationRuleUpdate,
        CreateAndModifyAutoModerationRuleParams,
        TriggerMetadata,
    )
    from .channels import (
        ArchivedThreadsResponse,
        Channel,
        ChannelCreate,
        ChannelDelete,
        ChannelPinsUpdate,
        ChannelUpdate,
        CreateGuildChannelParams,
        DefaultReaction,
        FollowedChannel,
        ForumTag,
        ForumTagRequest,
        ListActiveGuildThreadsResponse,
        ModifyChannelParams,
        ModifyGuildChannelPositionParams,
        ModifyThreadParams,
        Overwrite,
        PartialOverwrite,
        StartThreadFromMessageParams,
        StartThreadWithoutMessageParams,
        ThreadCreate,
        ThreadDelete,
        ThreadListSync,
        ThreadMember,
        ThreadMembersUpdate,
        ThreadMemberUpdate,
        ThreadMetadata,
        ThreadUpdate,
    )
    from .emoji import ApplicationEmojis, Emoji, ModifyGuildEmojiParams
    from .gateway import Gateway, GatewayBot, SessionStartLimit
    from .guild_members import (
        GuildMember,
        ModifyCurrentMemberParams,
        ModifyGuildMemberParams,
    )
    from .guild_scheduled_events import (
        CreateGuildScheduledEventParams,
        GuildScheduledEvent,
        GuildScheduledEventEntityMetadata,
        GuildScheduledEventRecurrenceRuleN_WeekdayStructure,
        GuildScheduledEventUser,
        ModifyGuildScheduledEventParams,
        RecurrenceRule,
    )
    from .guild_templates import (
        CreateGuildTemplateParams,
        GuildTemplate,
        GuildTemplateGuild,
        GuildTemplateGuildChannel,
        GuildTemplateGuildRole,
        ModifyGuildTemplateParams,
    )
    from .guild_welcome import (
        ModifyGuildWelcomeScreenParams,
        WelcomeScreen,
        WelcomeScreenChannel,
    )
    from .guilds import (
        Ban,
        BulkBan,
        CreateGuildParams,
        CurrentUserGuild,
        Guild,
        GuildAuditLogEntryCreate,
        GuildBanAdd,
        GuildBanRemove,
        GuildCreate,
        GuildCreateCompat,
        GuildCreateCompatChannel,
        GuildCreateCompatOverwrite,
        GuildCreateCompatRole,
        GuildDelete,
        GuildEmojisUpdate,
        GuildIncidentsData,
        GuildIntegrationsUpdate,
        GuildMemberAdd,
        GuildMemberRemove,
        GuildMembersChunk,
        GuildMemberUpdate,
        GuildOnboarding,
        GuildPreview,
        GuildRoleCreate,
        GuildRoleDelete,
        GuildRoleUpdate,
        GuildScheduledEventCreate,
        GuildScheduledEventDelete,
        GuildScheduledEventUpdate,
        GuildScheduledEventUserAdd,
        GuildScheduledEventUserRemove,
        GuildStickersUpdate,
        GuildUpdate,
        GuildVanityURL,
        GuildWidget,
        GuildWidgetChannel,
        GuildWidgetSettings,
        GuildWidgetUser,
        MembershipScreening,
        ModifyGuildIncidentActionsParams,
        ModifyGuildOnboardingParams,
        ModifyGuildParams,
        ModifyGuildWidgetParams,
        OnboardingPrompt,
        OnboardingPromptOption,
        UnavailableGuild,
    )
    from .integrations import (
        Integration,
        IntegrationAccount,
        IntegrationApplication,
        IntegrationCreate,
        IntegrationDelete,
        IntegrationUpdate,
    )
    from .invites import (
        Invite,
        InviteCreate,
        InviteDelete,
        InviteGuild,
        InviteMetadata,
        InviteStageInstance,
        InviteTargetUsersJobStatus,
    )
    from .lobby import (
        AddLobbyMemberParams,
        CreateLobbyMemberParams,
        CreateLobbyParams,
        LinkChannelToLobbyParams,
        Lobby,
        LobbyMember,
        ModifyLobbyParams,
    )
    from .monetization import (
        SKU,
        Entitlement,
        EntitlementCreate,
        EntitlementDelete,
        EntitlementUpdate,
        Subscription,
        SubscriptionCreate,
        SubscriptionDelete,
        SubscriptionUpdate,
    )
    from .polls import (
        AnswerVoters,
        Poll,
        PollAnswer,
        PollAnswerCount,
        PollAnswerRequest,
        PollMedia,
        PollRequest,
        PollResults,
    )
    from .soundboard import (
        CreateGuildSoundboardSoundParams,
        ListDefaultSoundboardSoundsResponse,
        ListGuildSoundboardSoundsResponse,
        ModifyGuildSoundboardSoundParams,
        SendSoundboardSoundParams,
        SoundboardSound,
    )
    from .stage_instance import StageInstance
    from .stickers import (
        ModifyGuildStickerParams,
        Sticker,
        StickerItem,
        StickerPack,
        StickerPacksResponse,
    )
    from .voice import ModifyCurrentUserVoiceStateParams, VoiceRegion, VoiceState
    from .webhooks import CreateWebhookParams, ExecuteWebhookParams, Webhook


__all__ = [
    "SKU",
    "ActivityInstance",
    "ActivityLocation",
    "AddLobbyMemberParams",
    "AnswerVoters",
    "Application",
    "ApplicationEmojis",
    "ApplicationIntegrationTypeConfiguration",
    "ApplicationRoleConnectionMetadata",
    "ArchivedThreadsResponse",
    "AuditLog",
    "AuditLogChange",
    "AuditLogChangeException",
    "AuditLogEntry",
    "AutoModerationAction",
    "AutoModerationActionExecution",
    "AutoModerationActionMetadata",
    "AutoModerationRule",
    "AutoModerationRuleCreate",
    "AutoModerationRuleDelete",
    "AutoModerationRuleUpdate",
    "Ban",
    "BulkBan",
    "Channel",
    "ChannelCreate",
    "ChannelDelete",
    "ChannelPinsUpdate",
    "ChannelUpdate",
    "CreateAndModifyAutoModerationRuleParams",
    "CreateGuildChannelParams",
    "CreateGuildParams",
    "CreateGuildScheduledEventParams",
    "CreateGuildSoundboardSoundParams",
    "CreateGuildTemplateParams",
    "CreateLobbyMemberParams",
    "CreateLobbyParams",
    "CreateWebhookParams",
    "CurrentUserGuild",
    "DefaultReaction",
    "EditCurrentApplicationParams",
    "Emoji",
    "Entitlement",
    "EntitlementCreate",
    "EntitlementDelete",
    "EntitlementUpdate",
    "ExecuteWebhookParams",
    "FollowedChannel",
    "ForumTag",
    "ForumTagRequest",
    "Gateway",
    "GatewayBot",
    "Guild",
    "GuildAuditLogEntryCreate",
    "GuildBanAdd",
    "GuildBanRemove",
    "GuildCreate",
    "GuildCreateCompat",
    "GuildCreateCompatChannel",
    "GuildCreateCompatOverwrite",
    "GuildCreateCompatRole",
    "GuildDelete",
    "GuildEmojisUpdate",
    "GuildIncidentsData",
    "GuildIntegrationsUpdate",
    "GuildMember",
    "GuildMemberAdd",
    "GuildMemberRemove",
    "GuildMemberUpdate",
    "GuildMembersChunk",
    "GuildOnboarding",
    "GuildPreview",
    "GuildRoleCreate",
    "GuildRoleDelete",
    "GuildRoleUpdate",
    "GuildScheduledEvent",
    "GuildScheduledEventCreate",
    "GuildScheduledEventDelete",
    "GuildScheduledEventEntityMetadata",
    "GuildScheduledEventRecurrenceRuleN_WeekdayStructure",
    "GuildScheduledEventUpdate",
    "GuildScheduledEventUser",
    "GuildScheduledEventUserAdd",
    "GuildScheduledEventUserRemove",
    "GuildStickersUpdate",
    "GuildTemplate",
    "GuildTemplateGuild",
    "GuildTemplateGuildChannel",
    "GuildTemplateGuildRole",
    "GuildUpdate",
    "GuildVanityURL",
    "GuildWidget",
    "GuildWidgetChannel",
    "GuildWidgetSettings",
    "GuildWidgetUser",
    "InstallParams",
    "Integration",
    "IntegrationAccount",
    "IntegrationApplication",
    "IntegrationCreate",
    "IntegrationDelete",
    "IntegrationUpdate",
    "Invite",
    "InviteCreate",
    "InviteDelete",
    "InviteGuild",
    "InviteMetadata",
    "InviteStageInstance",
    "InviteTargetUsersJobStatus",
    "LinkChannelToLobbyParams",
    "ListActiveGuildThreadsResponse",
    "ListDefaultSoundboardSoundsResponse",
    "ListGuildSoundboardSoundsResponse",
    "Lobby",
    "LobbyMember",
    "MembershipScreening",
    "ModifyChannelParams",
    "ModifyCurrentMemberParams",
    "ModifyCurrentUserVoiceStateParams",
    "ModifyGuildChannelPositionParams",
    "ModifyGuildEmojiParams",
    "ModifyGuildIncidentActionsParams",
    "ModifyGuildMemberParams",
    "ModifyGuildOnboardingParams",
    "ModifyGuildParams",
    "ModifyGuildScheduledEventParams",
    "ModifyGuildSoundboardSoundParams",
    "ModifyGuildStickerParams",
    "ModifyGuildTemplateParams",
    "ModifyGuildWelcomeScreenParams",
    "ModifyGuildWidgetParams",
    "ModifyLobbyParams",
    "ModifyThreadParams",
    "OnboardingPrompt",
    "OnboardingPromptOption",
    "OptionalAuditEntryInfo",
    "Overwrite",
    "PartialOverwrite",
    "Poll",
    "PollAnswer",
    "PollAnswerCount",
    "PollAnswerRequest",
    "PollMedia",
    "PollRequest",
    "PollResults",
    "RecurrenceRule",
    "SendSoundboardSoundParams",
    "SessionStartLimit",
    "SoundboardSound",
    "StageInstance",
    "StartThreadFromMessageParams",
    "StartThreadWithoutMessageParams",
    "Sticker",
    "StickerItem",
    "StickerPack",
    "StickerPacksResponse",
    "Subscription",
    "SubscriptionCreate",
    "SubscriptionDelete",
    "SubscriptionUpdate",
    "ThreadCreate",
    "ThreadDelete",
    "ThreadListSync",
    "ThreadMember",
    "ThreadMemberUpdate",
    "ThreadMembersUpdate",
    "ThreadMetadata",
    "ThreadUpdate",
    "TriggerMetadata",
    "UnavailableGuild",
    "VoiceRegion",
    "VoiceState",
    "Webhook",
    "WelcomeScreen",
    "WelcomeScreenChannel",
]


_EXPORTS: dict[str, tuple[str, str]] = {
    "ActivityInstance": (".application", "ActivityInstance"),
    "ActivityLocation": (".application", "ActivityLocation"),
    "Application": (".application", "Application"),
    "ApplicationIntegrationTypeConfiguration": (
        ".application",
        "ApplicationIntegrationTypeConfiguration",
    ),
    "ApplicationRoleConnectionMetadata": (
        ".application",
        "ApplicationRoleConnectionMetadata",
    ),
    "EditCurrentApplicationParams": (".application", "EditCurrentApplicationParams"),
    "InstallParams": (".application", "InstallParams"),
    "AuditLog": (".audit_log", "AuditLog"),
    "AuditLogChange": (".audit_log", "AuditLogChange"),
    "AuditLogChangeException": (".audit_log", "AuditLogChangeException"),
    "AuditLogEntry": (".audit_log", "AuditLogEntry"),
    "OptionalAuditEntryInfo": (".audit_log", "OptionalAuditEntryInfo"),
    "AutoModerationAction": (".auto_moderation", "AutoModerationAction"),
    "AutoModerationActionExecution": (
        ".auto_moderation",
        "AutoModerationActionExecution",
    ),
    "AutoModerationActionMetadata": (
        ".auto_moderation",
        "AutoModerationActionMetadata",
    ),
    "AutoModerationRule": (".auto_moderation", "AutoModerationRule"),
    "AutoModerationRuleCreate": (".auto_moderation", "AutoModerationRuleCreate"),
    "AutoModerationRuleDelete": (".auto_moderation", "AutoModerationRuleDelete"),
    "AutoModerationRuleUpdate": (".auto_moderation", "AutoModerationRuleUpdate"),
    "CreateAndModifyAutoModerationRuleParams": (
        ".auto_moderation",
        "CreateAndModifyAutoModerationRuleParams",
    ),
    "TriggerMetadata": (".auto_moderation", "TriggerMetadata"),
    "ArchivedThreadsResponse": (".channels", "ArchivedThreadsResponse"),
    "Channel": (".channels", "Channel"),
    "ChannelCreate": (".channels", "ChannelCreate"),
    "ChannelDelete": (".channels", "ChannelDelete"),
    "ChannelPinsUpdate": (".channels", "ChannelPinsUpdate"),
    "ChannelUpdate": (".channels", "ChannelUpdate"),
    "CreateGuildChannelParams": (".channels", "CreateGuildChannelParams"),
    "DefaultReaction": (".channels", "DefaultReaction"),
    "FollowedChannel": (".channels", "FollowedChannel"),
    "ForumTag": (".channels", "ForumTag"),
    "ForumTagRequest": (".channels", "ForumTagRequest"),
    "ListActiveGuildThreadsResponse": (".channels", "ListActiveGuildThreadsResponse"),
    "ModifyChannelParams": (".channels", "ModifyChannelParams"),
    "ModifyGuildChannelPositionParams": (
        ".channels",
        "ModifyGuildChannelPositionParams",
    ),
    "ModifyThreadParams": (".channels", "ModifyThreadParams"),
    "Overwrite": (".channels", "Overwrite"),
    "PartialOverwrite": (".channels", "PartialOverwrite"),
    "StartThreadFromMessageParams": (".channels", "StartThreadFromMessageParams"),
    "StartThreadWithoutMessageParams": (
        ".channels",
        "StartThreadWithoutMessageParams",
    ),
    "ThreadCreate": (".channels", "ThreadCreate"),
    "ThreadDelete": (".channels", "ThreadDelete"),
    "ThreadListSync": (".channels", "ThreadListSync"),
    "ThreadMember": (".channels", "ThreadMember"),
    "ThreadMembersUpdate": (".channels", "ThreadMembersUpdate"),
    "ThreadMemberUpdate": (".channels", "ThreadMemberUpdate"),
    "ThreadMetadata": (".channels", "ThreadMetadata"),
    "ThreadUpdate": (".channels", "ThreadUpdate"),
    "ApplicationEmojis": (".emoji", "ApplicationEmojis"),
    "Emoji": (".emoji", "Emoji"),
    "ModifyGuildEmojiParams": (".emoji", "ModifyGuildEmojiParams"),
    "Gateway": (".gateway", "Gateway"),
    "GatewayBot": (".gateway", "GatewayBot"),
    "SessionStartLimit": (".gateway", "SessionStartLimit"),
    "GuildMember": (".guild_members", "GuildMember"),
    "ModifyCurrentMemberParams": (".guild_members", "ModifyCurrentMemberParams"),
    "ModifyGuildMemberParams": (".guild_members", "ModifyGuildMemberParams"),
    "CreateGuildScheduledEventParams": (
        ".guild_scheduled_events",
        "CreateGuildScheduledEventParams",
    ),
    "GuildScheduledEvent": (".guild_scheduled_events", "GuildScheduledEvent"),
    "GuildScheduledEventEntityMetadata": (
        ".guild_scheduled_events",
        "GuildScheduledEventEntityMetadata",
    ),
    "GuildScheduledEventRecurrenceRuleN_WeekdayStructure": (
        ".guild_scheduled_events",
        "GuildScheduledEventRecurrenceRuleN_WeekdayStructure",
    ),
    "GuildScheduledEventUser": (".guild_scheduled_events", "GuildScheduledEventUser"),
    "ModifyGuildScheduledEventParams": (
        ".guild_scheduled_events",
        "ModifyGuildScheduledEventParams",
    ),
    "RecurrenceRule": (".guild_scheduled_events", "RecurrenceRule"),
    "CreateGuildTemplateParams": (".guild_templates", "CreateGuildTemplateParams"),
    "GuildTemplate": (".guild_templates", "GuildTemplate"),
    "GuildTemplateGuild": (".guild_templates", "GuildTemplateGuild"),
    "GuildTemplateGuildChannel": (".guild_templates", "GuildTemplateGuildChannel"),
    "GuildTemplateGuildRole": (".guild_templates", "GuildTemplateGuildRole"),
    "ModifyGuildTemplateParams": (".guild_templates", "ModifyGuildTemplateParams"),
    "ModifyGuildWelcomeScreenParams": (
        ".guild_welcome",
        "ModifyGuildWelcomeScreenParams",
    ),
    "WelcomeScreen": (".guild_welcome", "WelcomeScreen"),
    "WelcomeScreenChannel": (".guild_welcome", "WelcomeScreenChannel"),
    "Ban": (".guilds", "Ban"),
    "BulkBan": (".guilds", "BulkBan"),
    "CreateGuildParams": (".guilds", "CreateGuildParams"),
    "CurrentUserGuild": (".guilds", "CurrentUserGuild"),
    "Guild": (".guilds", "Guild"),
    "GuildAuditLogEntryCreate": (".guilds", "GuildAuditLogEntryCreate"),
    "GuildBanAdd": (".guilds", "GuildBanAdd"),
    "GuildBanRemove": (".guilds", "GuildBanRemove"),
    "GuildCreate": (".guilds", "GuildCreate"),
    "GuildCreateCompat": (".guilds", "GuildCreateCompat"),
    "GuildCreateCompatChannel": (".guilds", "GuildCreateCompatChannel"),
    "GuildCreateCompatOverwrite": (".guilds", "GuildCreateCompatOverwrite"),
    "GuildCreateCompatRole": (".guilds", "GuildCreateCompatRole"),
    "GuildDelete": (".guilds", "GuildDelete"),
    "GuildEmojisUpdate": (".guilds", "GuildEmojisUpdate"),
    "GuildIncidentsData": (".guilds", "GuildIncidentsData"),
    "GuildIntegrationsUpdate": (".guilds", "GuildIntegrationsUpdate"),
    "GuildMemberAdd": (".guilds", "GuildMemberAdd"),
    "GuildMemberRemove": (".guilds", "GuildMemberRemove"),
    "GuildMembersChunk": (".guilds", "GuildMembersChunk"),
    "GuildMemberUpdate": (".guilds", "GuildMemberUpdate"),
    "GuildOnboarding": (".guilds", "GuildOnboarding"),
    "GuildPreview": (".guilds", "GuildPreview"),
    "GuildRoleCreate": (".guilds", "GuildRoleCreate"),
    "GuildRoleDelete": (".guilds", "GuildRoleDelete"),
    "GuildRoleUpdate": (".guilds", "GuildRoleUpdate"),
    "GuildScheduledEventCreate": (".guilds", "GuildScheduledEventCreate"),
    "GuildScheduledEventDelete": (".guilds", "GuildScheduledEventDelete"),
    "GuildScheduledEventUpdate": (".guilds", "GuildScheduledEventUpdate"),
    "GuildScheduledEventUserAdd": (".guilds", "GuildScheduledEventUserAdd"),
    "GuildScheduledEventUserRemove": (".guilds", "GuildScheduledEventUserRemove"),
    "GuildStickersUpdate": (".guilds", "GuildStickersUpdate"),
    "GuildUpdate": (".guilds", "GuildUpdate"),
    "GuildVanityURL": (".guilds", "GuildVanityURL"),
    "GuildWidget": (".guilds", "GuildWidget"),
    "GuildWidgetChannel": (".guilds", "GuildWidgetChannel"),
    "GuildWidgetSettings": (".guilds", "GuildWidgetSettings"),
    "GuildWidgetUser": (".guilds", "GuildWidgetUser"),
    "MembershipScreening": (".guilds", "MembershipScreening"),
    "ModifyGuildIncidentActionsParams": (
        ".guilds",
        "ModifyGuildIncidentActionsParams",
    ),
    "ModifyGuildOnboardingParams": (".guilds", "ModifyGuildOnboardingParams"),
    "ModifyGuildParams": (".guilds", "ModifyGuildParams"),
    "ModifyGuildWidgetParams": (".guilds", "ModifyGuildWidgetParams"),
    "OnboardingPrompt": (".guilds", "OnboardingPrompt"),
    "OnboardingPromptOption": (".guilds", "OnboardingPromptOption"),
    "UnavailableGuild": (".guilds", "UnavailableGuild"),
    "Integration": (".integrations", "Integration"),
    "IntegrationAccount": (".integrations", "IntegrationAccount"),
    "IntegrationApplication": (".integrations", "IntegrationApplication"),
    "IntegrationCreate": (".integrations", "IntegrationCreate"),
    "IntegrationDelete": (".integrations", "IntegrationDelete"),
    "IntegrationUpdate": (".integrations", "IntegrationUpdate"),
    "Invite": (".invites", "Invite"),
    "InviteCreate": (".invites", "InviteCreate"),
    "InviteDelete": (".invites", "InviteDelete"),
    "InviteGuild": (".invites", "InviteGuild"),
    "InviteMetadata": (".invites", "InviteMetadata"),
    "InviteStageInstance": (".invites", "InviteStageInstance"),
    "InviteTargetUsersJobStatus": (".invites", "InviteTargetUsersJobStatus"),
    "AddLobbyMemberParams": (".lobby", "AddLobbyMemberParams"),
    "CreateLobbyMemberParams": (".lobby", "CreateLobbyMemberParams"),
    "CreateLobbyParams": (".lobby", "CreateLobbyParams"),
    "LinkChannelToLobbyParams": (".lobby", "LinkChannelToLobbyParams"),
    "Lobby": (".lobby", "Lobby"),
    "LobbyMember": (".lobby", "LobbyMember"),
    "ModifyLobbyParams": (".lobby", "ModifyLobbyParams"),
    "SKU": (".monetization", "SKU"),
    "Entitlement": (".monetization", "Entitlement"),
    "EntitlementCreate": (".monetization", "EntitlementCreate"),
    "EntitlementDelete": (".monetization", "EntitlementDelete"),
    "EntitlementUpdate": (".monetization", "EntitlementUpdate"),
    "Subscription": (".monetization", "Subscription"),
    "SubscriptionCreate": (".monetization", "SubscriptionCreate"),
    "SubscriptionDelete": (".monetization", "SubscriptionDelete"),
    "SubscriptionUpdate": (".monetization", "SubscriptionUpdate"),
    "AnswerVoters": (".polls", "AnswerVoters"),
    "Poll": (".polls", "Poll"),
    "PollAnswer": (".polls", "PollAnswer"),
    "PollAnswerCount": (".polls", "PollAnswerCount"),
    "PollAnswerRequest": (".polls", "PollAnswerRequest"),
    "PollMedia": (".polls", "PollMedia"),
    "PollRequest": (".polls", "PollRequest"),
    "PollResults": (".polls", "PollResults"),
    "CreateGuildSoundboardSoundParams": (
        ".soundboard",
        "CreateGuildSoundboardSoundParams",
    ),
    "ListDefaultSoundboardSoundsResponse": (
        ".soundboard",
        "ListDefaultSoundboardSoundsResponse",
    ),
    "ListGuildSoundboardSoundsResponse": (
        ".soundboard",
        "ListGuildSoundboardSoundsResponse",
    ),
    "ModifyGuildSoundboardSoundParams": (
        ".soundboard",
        "ModifyGuildSoundboardSoundParams",
    ),
    "SendSoundboardSoundParams": (".soundboard", "SendSoundboardSoundParams"),
    "SoundboardSound": (".soundboard", "SoundboardSound"),
    "StageInstance": (".stage_instance", "StageInstance"),
    "ModifyGuildStickerParams": (".stickers", "ModifyGuildStickerParams"),
    "Sticker": (".stickers", "Sticker"),
    "StickerItem": (".stickers", "StickerItem"),
    "StickerPack": (".stickers", "StickerPack"),
    "StickerPacksResponse": (".stickers", "StickerPacksResponse"),
    "ModifyCurrentUserVoiceStateParams": (
        ".voice",
        "ModifyCurrentUserVoiceStateParams",
    ),
    "VoiceRegion": (".voice", "VoiceRegion"),
    "VoiceState": (".voice", "VoiceState"),
    "CreateWebhookParams": (".webhooks", "CreateWebhookParams"),
    "ExecuteWebhookParams": (".webhooks", "ExecuteWebhookParams"),
    "Webhook": (".webhooks", "Webhook"),
}


def __getattr__(name: str) -> object:
    try:
        module_name, attr_name = _EXPORTS[name]
    except KeyError:
        raise AttributeError(name) from None

    module = import_module(module_name, __name__)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
